### ISSUE TITLE
Received error HTTP response code: 400

### ISSUE THREAD

**Issue by snail9527** [googleads/googleads-mobile-android-examples#100]
I found same issue #68 ,but i don't known how to fit it

12-14 15:44:54.648 11859 11859 D Ads     : App is still foreground.
12-14 15:44:54.855 11859 11859 I Ads     : Starting ad request.
12-14 15:44:54.856 11859 11859 I Ads     : Use AdRequest.Builder.addTestDevice("056B496EBDB0E1DB2D6548196F7604AD") to ge
t test ads on this device.
12-14 15:44:54.858 11859 11859 I Ads     : Webview loading for native ads.
12-14 15:44:54.878 15696 15696 D Ads     : Binding to the ad cache service.
12-14 15:44:54.989 11859 11859 D Ads     : Enabling hardware acceleration on an AdView.
12-14 15:44:55.063 11859 16991 D Ads     : AdLoaderBackgroundTask started.
12-14 15:44:55.092 11859 16994 D Ads     : Fetching ad response from remote ad request service.
12-14 15:44:55.125 15696 15696 D Ads     : Binding to the ad request service.
12-14 15:44:55.214 15696 17001 D Ads     : Starting ad request from service using: google.afma.request.getAdDictionary
12-14 15:44:55.299 11859 11859 I Ads     : Javascript has loaded for native ads.
12-14 15:44:55.344 15696 17005 D Ads     : Got 2 signal pbs from gmscore
12-14 15:44:55.359 15696 17005 D Ads     : Merged client and gmscore signals
12-14 15:44:55.359 15696 17005 D Ads     : Return the combined signals
12-14 15:44:55.424 15696 17007 D Ads     : Fail to obtain recent context.
12-14 15:44:55.625 15696 17001 D Ads     : AdRequestServiceImpl: Sending request: https://googleads.g.doubleclick.net/ma
ds/gma?carrier=46000&riv=0&native_image_orientation=landscape&_activity_context=false&format=320x50_mb&gl=CN&seq_num=9&e
id=318475406%2C318478658%2C318479096%2C318478902&u_sd=3&ms=CpUCCoACs7Y4V5YUKG0fMJOpV31bsruMANfNEu5KzrSFdOp1XVHLis2r7L13e
OTNNWDvQqS4AtH0OFiqdf9lhn9BAOPNubofp-kLCKrRBhfynbmQYiy89Ow-ThF5VnJmIo8GJemXUjFNp0Mpv4EZCjrvpdi-Mj8491HPSLkE_XYbtbkOQL-En
YSlhWbq5nogO34t8Nk700wgMZ_MUO6RsFEL1xMgIMTEyHA6wswn0JpRkMWBEWtSjZIOPgrd-7dqRIRFtJCrdhV_EcY1BRbImexU05uBsjr3_SdJXkeI25fvk
OjDEl3NVbXW1PeDCDVPr8qnHxM8gcNyeslWpOgbjYbRnDtRPxIQ8QNqi7HuSQB_YRce4qqIqRKVAgqAAhlhr8pBTC_yvG0ORZ7qDzqaBGtV1NZvp4JIU20E1
qOC8MZfO3iYwyri-xRCJD1L_ZdGfSyYpwgHss22rWiP0EI3havYNa9gZ04WFdVzNGv4j0Nuf2t2L-du45mv4yKgfn4NzT405xj2Elqad7RaRFUQuKhI89Rup
VXQ8hVHgzTPCCJKON31JMr2B8H_eGjIE20e8C7Pt6_inT5okXoiNEdrZ0O3QxncmomSLK0mACGBX5MP4pOQiL-hR1pP6KdQhXvz_ze9XauEPogtp0099N2jj
qn2SIB-iiSwokdvl3gHhcYOlWL7is9KBTwBZWMFiCF1EqwtTXbYXvNMJGkw_HMSEAFYsgWESCkuJ-lBXZcqvaQ&target_api=19&hl=zh-CN&scroll_ind
ex=-1&platform=HUAWEI&submodel=NEM-TL00H&rm=0&max_num_ads=2&android_app_muted=false&request_id=74825edf-7761-4418-98c8-3
9626dc9c0ec&am=0&cnt=1&ma=0&disable_ml=false&js=afma-sdk-a-v11951448.11717000.1&session_id=6091722045937925252&native_te
mplates=1%2C2%2C4%2C5&muv=5&coh=1&sp=1&forceHttps=true&gnt=13&mv=80841900.com.android.vending&native_version=3&android_a
pp_volume=1&android_num_video_cache_tasks=0&u_w=360&u_h=604&msid=com.launcher.s.plus&app_name=14.android.com.launcher.s.
plus&_package_name=com.launcher.s.plus&an=14.android.com.launcher.s.plus&net=wi&u_audio=3&u_so=p&basets=242783550&currts
=243682478&preqs_in_session=11&pclick=0&support_transparent_background=true&pimp=0&preqs=8&time_in_session=1139582&outpu
t=html&region=mobile_app&u_tz=480&client_sdk=1&ex=1&client=ca-app-pub-7127448265484229&slotname=8069979830&askip=3&gsb=w
i&local_service=false&lite=true&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transp
arentBackground_sdkAdmobApiForAds_di_sfv_dinm_dim_nav_navc_dinmo_gcache&bisch=true&blev=0.64&swdr=false&cans=5&canm=fals
e&_mv=23.com.huawei.android.internal.app&pscfas=true&heap_free=92752&heap_max=536870912&heap_total=63289456&wv_count=2&s
ai=1&mr=-411032102915966907%2C1141485994923993463%2C2385822614828646595%2C2709630492198784947%2C3047866116356412499%2C48
66698085148993459%2C6203041992259012537%2C8660954740221421619%2C-2947986919139247086%2C-3961489171451239700%2C-696200025
9256540789&blockAutoClicks=false&includeDoritos=true&content_infol=-1&blob=ABPQqLFxkfg2-DWXD0E_uPh9xYFBwfoXr1Z7eHf5OI-tk
f3SQknDdcJJK3M1dF4YR7yzxni_wHxKW71SE21Bnw2xuUDDcO5-xBAVEtFYBH2iDtzpPiXDADyOdvVefJPEMtCBIyjlCAUCkNvaeH5ar2HwMETnw_KZcPZAM
nVOBmhAvkYimwDxAfTZ6ONonDoOcSKqJ62vmnll9q_T-HxkDUxlda6dGaSTKhcnqy9N7dIi_I_hv_Ut2lG7n4MVew&et=39&swipeable=0&tcar=94&jsv=
4-production-20171211_RC00&urll=2824&sra_urls=slotname%3D8069979830%2Cslotname%3D8069979830#_activity_context=false&andr
oid_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparen
tBackground_sdkAdmobApiForAds_di_sfv_dinm_dim_nav_navc_dinmo_gcache&eid=318475406%252C318478658%252C318479096%252C318478
902&format=320x50_mb&heap_free=92752&heap_max=536870912&heap_total=63289456&js=afma-sdk-a-v11951448.11717000.1&mr=-41103
2102915966907%252C1141485994923993463%252C2385822614828646595%252C2709630492198784947%252C3047866116356412499%252C486669
8085148993459%252C6203041992259012537%252C8660954740221421619%252C-2947986919139247086%252C-3961489171451239700%252C-696
2000259256540789&msid=com.launcher.s.plus&preqs=8&scroll_index=-1&seq_num=9&target_api=19
12-14 15:44:55.940 15696 17001 W Ads     : Received error HTTP response code: 400
12-14 15:44:55.942 11859 11869 D Ads     : Received ad response.
12-14 15:44:55.943 11859 11869 W Ads     : There was a problem getting an ad response. ErrorCode: 0
12-14 15:44:55.945 11859 11859 W Ads     : Failed to load ad: 0
12-14 15:44:55.945 11859 11859 D Ads     : Enable the debug gesture detector on the admob ad frame.

**Comment by ericleich** [comment]
How soon after this ad unit was created did you try to load ads? It takes about an hour for ad units to start serving - I'd like to rule that out.

**Comment by snail9527** [comment]
Thank you for your answer, The ad unit was created for a few days, I found some answer online. it seem that it have to completed setting up the AdMob account for payments. i will talk with our pm.

**Comment by ericleich** [comment]
For what it's worth, I see some traffic in your account now. It appears to be working at this point, so I'm going to close this issue.
