### ISSUE TITLE
Fail to instantiate adapter com.google.DummyAdapter

### ISSUE THREAD

**Issue by huyongli** [googleads/googleads-mobile-android-examples#102]
Failed to load ad: 3  and Fail to instantiate adapter com.google.DummyAdapter

**Comment by ericleich** [comment]
This is a somewhat misleading message, it just means no fill. Did this happen when using the sample ad units?

**Comment by huyongli** [comment]
@ericleich  Yes, using the sample ad units have same problem

**Comment by stowy** [comment]
@huyongli if this is occurring in a sample app, can you please advise which sample app it is and steps to reproduce the issue?

**Comment by stowy** [comment]
closing as unable to reproduce.
