### ISSUE TITLE
replace ADMOB_AD_UNIT_ID and ADMOB_APP_ID after not get ads

### ISSUE THREAD

**Issue by FangWW** [googleads/googleads-mobile-android-examples#103]
https://github.com/googleads/googleads-mobile-android-examples/blob/01e24905175a26f6721b4f50faba1cd06d378f31/java/admob/NativeAdvancedExample/app/src/main/java/com/google/example/gms/nativeadvancedexample/MainActivity.java#L52

replace ADMOB_AD_UNIT_ID and ADMOB_APP_ID after not get ad!
because The native express ad format is being discontinued.
I want to replace him with native ads and use his AD unit id directly.
bug 

12-20 10:29:54.961 14815-15838/com.w.schulte W/Ads: Received error HTTP response code: 403
12-20 10:29:54.962 14815-15838/com.w.schulte W/Ads: There was a problem getting an ad response. ErrorCode: 0
12-20 10:29:54.965 14815-14815/com.w.schulte W/Ads: Failed to load ad: 0

I don't know if I'm going to create that type of advertising to use native ads

Can you help me? Thank you

**Comment by ericleich** [comment]
2 likely reasons for the issue:

1) Is the AdMob ad unit ID you're using a "native advanced" ad unit? Note that native express ad units do not work when requesting ads.
2) Are you testing on device? App install ads won't work when testing on emulators, because the emulator doesn't have the play store on it.

**Comment by FangWW** [comment]
Hello,
1,I don`t use emulators
2,Admob select ad format only "Banner" ,"Interstitial","Rewarded", I use "native advanced" demo,I should create that AD unit? 

Then replace him:
https://github.com/googleads/googleads-mobile-android-examples/blob/01e24905175a26f6721b4f50faba1cd06d378f31/java/admob/NativeAdvancedExample/app/src/main/java/com/google/example/gms/nativeadvancedexample/MainActivity.java#L52

**Comment by ericleich** [comment]
Native advanced is still limited access. If you don't have the ability to create a "Native Advanced" ad unit in the AdMob UI, then banner ads is the recommended format to migrate to.

**Comment by FangWW** [comment]
Why am I not authorized to use Native advanced? I don't seem to have found relevant instructions in the document.
If I want to make a start page AD, the banner AD is too small and the effect is not very good.Which existing type of advertisement should I choose?

**Comment by FangWW** [comment]
sorry,
I find "Note: Native Ads Advanced is currently in a limited release. If you're interested in participating, reach out to your account manager to discuss the possibility."  

If I want to make a start page AD, the banner AD is too small and the effect is not very good.Which existing type of advertisement should I choose?

**Comment by stowy** [comment]
@FangWW what size ad do you need? There are a number of [banner ad sizes available](https://developers.google.com/admob/android/banner#banner_sizes).
