### ISSUE TITLE
Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by karopass** [googleads/googleads-mobile-android-examples#106]
Hi!
I am facing issue like 
`java.lang.IllegalStateException: Only fullscreen activities can request orientation`
during display Interstitial ads when I set target version of application to 27. If I use 26 then no issue coming. Please check and solve it.
Thanks

**Comment by RedBrogdon** [comment]
Thanks for reporting the problem.

This is a known issue in the Android SDK, and the engineering team has prepared a fix that will go out in the next release. In the meantime, compiling against API level 26 is the correct workaround.
