### ISSUE TITLE
What are required fields of a native banner?

### ISSUE THREAD

**Issue by ghost** [googleads/googleads-mobile-android-examples#108]
Good morning Sirs,

Could you please list all required fields of a native banner? I wish to use some fields, not all. So it will helps my app a lot.

**Comment by stowy** [comment]
Hi, thanks for your query.

I'm not sure what you are referring to when you say 'required fields'. When you refer to native banner, are you referring to [Native Ads Advanced](https://developers.google.com/admob/android/native-advanced)? If so, please note this is a limited beta feature, and if you have questions you should reach out to your account manager. If you do have access to the Native Ads Advanced beta, you might want to refer to [this article](https://support.google.com/admob/answer/6240809).

Also please note that these github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details about which feature you are trying to implement and possibly include code snippets of your implementation to help the forum support understand your situation more clearly.

Regards

Sam
