### ISSUE TITLE
What required fields of a native banner are?

### ISSUE THREAD

**Issue by ghost** [googleads/googleads-mobile-android-examples#109]
Good morning Sirs,

I wish to use some fields, not all. So could you list required fields of a native banner? It will helps my app a lot.

For fields, I mean: body, image, headline, provider, app icon...

**Comment by stowy** [comment]
Hi, thanks for your query.

I previously responded to [your other issue](https://github.com/googleads/googleads-mobile-android-examples/issues/108). Including my response below.

It looks like you are referring to [Native Ads Advanced](https://developers.google.com/admob/android/native-advanced). If so, please note this is a limited beta feature, and if you have questions you should reach out to your account manager. If you do have access to the Native Ads Advanced beta, you might want to refer to [this article](https://support.google.com/admob/answer/6240809) which outlines the required versus recommended fields.  Also please review the [implementation guide](https://developers.google.com/admob/android/native-advanced).

To check if you have access, I suggest trying to create an Ad Unit in your [Admob](https://www.google.com/admob/) account.

Also please note that these github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details about which feature you are trying to implement and possibly include code snippets of your implementation to help the forum support understand your situation more clearly.

Regards

Sam
