### ISSUE TITLE
There was a problem getting an ad response. ErrorCode: 0

### ISSUE THREAD

**Issue by poikl369** [googleads/googleads-mobile-android-examples#110]
02-27 09:59:15.652 9252-9252/? I/Ads: Updating ad debug logging enablement.
02-27 09:59:15.671 9252-9252/? I/Ads: Starting ad request.
02-27 09:59:15.672 9252-9252/? I/Ads: This request is sent from a test device.
02-27 09:59:15.674 9252-9252/? W/Ads: Not retrying to fetch app settings
02-27 09:59:15.780 9252-9335/? W/Ads: Update ad debug logging enablement as false
02-27 09:59:17.423 9252-9326/app.ymusic.android W/Ads: There was a problem getting an ad response. ErrorCode: 0
02-27 09:59:17.427 9252-9252/app.ymusic.android W/Ads: Failed to load ad: 0
02-27 09:59:17.429 9252-9252/app.ymusic.android I/chromium: [INFO:CONSOLE(0)] "Creating Application Cache with manifest https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.appcache", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
02-27 09:59:17.430 9252-9252/app.ymusic.android I/chromium: [INFO:CONSOLE(0)] "Application Cache Checking event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
02-27 09:59:17.839 9252-9252/app.ymusic.android I/chromium: [INFO:CONSOLE(0)] "Application Cache Downloading event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
02-27 09:59:17.840 9252-9252/app.ymusic.android I/chromium: [INFO:CONSOLE(0)] "Application Cache Progress event (0 of 2) https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.js", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
02-27 09:59:18.878 9252-9252/app.ymusic.android I/chromium: [INFO:CONSOLE(0)] "Application Cache Progress event (1 of 2) https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
02-27 09:59:19.332 9252-9252/app.ymusic.android I/chromium: [INFO:CONSOLE(0)] "Application Cache Progress event (2 of 2) ", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
02-27 09:59:19.334 9252-9252/app.ymusic.android I/chromium: [INFO:CONSOLE(0)] "Application Cache Cached event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
02-27 09:59:22.828 9252-9252/app.ymusic.android I/Ads: Starting ad request.
02-27 09:59:22.828 9252-9252/app.ymusic.android I/Ads: This request is sent from a test device.
02-27 09:59:23.430 9252-9264/app.ymusic.android W/Ads: There was a problem getting an ad response. ErrorCode: 0
02-27 09:59:23.431 9252-9252/app.ymusic.android W/Ads: Failed to load ad: 0

unitId : ca-app-pub-3370634603309531/8652015214

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

That said, the error code appears to be 0 - [ERROR_CODE_INTERNAL_ERROR](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest.html#ERROR_CODE_INTERNAL_ERROR). So please include steps in your forum post on how to reproduce the issue. 

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
