### ISSUE TITLE
Interstitial doesn't launch during android multi-window

### ISSUE THREAD

**Issue by kford55** [googleads/googleads-mobile-android-examples#112]
Putting the interstitial example into android multi-window causes the interstitial to never launch. The timer just restarts with no interstitial shown. This does not happen on windowed mode on Android on Chrome OS.

Running on a Pixel 2 xl on 8.1.0

**Comment by stowy** [comment]
Hi @kford55, thanks, yes we are able to replicate this issue. I will report the bug and advise of any updates.

**Comment by stowy** [comment]
I retested this in Android 8 and Android 9 at the advice of our engineers, using version 17.1.1, and found that the issue no longer reproduces.
