### ISSUE TITLE
error: file not found (values-ldltr-v21.xml)

### ISSUE THREAD

**Issue by zboing** [googleads/googleads-mobile-android-examples#116]
googleads-mobile-android-examples-master\java\admob\NativeAdvancedExample\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-ldltr-v21\values-ldltr-v21.xml
error: file not found

The above error appears when trying to import the project NativeAdvancedExample althouth the file exists in the location.

values-ldltr-v21.xml file content is : 
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Base.Widget.AppCompat.Spinner.Underlined" parent="android:Widget.Material.Spinner.Underlined"/>
</resources>

**Comment by stowy** [comment]
Hi,

This issue doesn't replicate for me when I download and import the NativeAdvancedExample. Have you tried cleaning and rebuilding the project?

If so, can you provide steps to reproduce this issue?

**Comment by zboing** [comment]
This happens due to AAPT2's limitation with paths on windows. It currently has issues with paths containing non-ascii characters and paths longer than circa 145 characters. 
This has been marked as fixed in the android issue tracker, but the fix hasn't been released yet.

Not a bug on admob side

**Comment by stowy** [comment]
thanks @zboing for tracking down the cause and letting us know!
