### ISSUE TITLE
Interstitial Ads add CountDownTimer button ？？？

### ISSUE THREAD

**Issue by TonyJason** [googleads/googleads-mobile-android-examples#118]
Hello, I would like to ask how to add a CountDownTimer button to the top right-hand corner of the insert type Interstitial Ads. Like this picture ,Thank
![image](https://user-images.githubusercontent.com/15902558/39195700-f19ce1aa-4812-11e8-912e-427488fad047.png)

**Comment by stowy** [comment]
Hi @TonyJason thanks for your query. This feature is controlled by advertisers, there is no option to modify creatives (advertisements) on the publisher side.

**Comment by fcscr126608** [comment]
thanks
I have another question: Banner Ads always return:Ads  No fill from ad server.Failed to load ad: 3
and Ads  set adSize is SMART_BANNER
How should I solve it
