### ISSUE TITLE
why error code =0?

### ISSUE THREAD

**Issue by qssq** [googleads/googleads-mobile-android-examples#120]
我用官方的appid 是没有问题的，但是把 app id和广告位id修改为自己的就无法正常显示广告了。
I use the official appid is no problem, but the app ID and advertising ID modified to their own can not display the ads.

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
