### ISSUE TITLE
error

### ISSUE THREAD

**Issue by amin9565** [googleads/googleads-mobile-android-examples#122]
hello thank you for tutorial (interstitial).
i add to codes in my project and when click retry button show toast : ad did not load 
in logcat in android studio written :
 I/Ads: No fill from ad server.
 W/Ads: Failed to load ad: 3
what do i do ? 
thanks

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.

That said, if you are getting no fill, I would recommend [enabling test ads](https://developers.google.com/admob/android/test-ads), as you will always receive ads with test ads enabled. You should not load live ads in testing as this is against policy.
