### ISSUE TITLE
How can I check if the user got rewarded, even if he uninstalled&re-installed the app?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-examples#123]
Is there an API for this? Maybe even know when was the last time he got rewarded? Or even history of rewards?
For example, I'd like to reward the user of watching a video, by removing banners.﻿

**Comment by stowy** [comment]
Hi,

Yes, please refer to the [rewarded video documentation](https://developers.google.com/admob/android/rewarded-video#set_up_event_notifications) for information on the rewarded video listener.

Also for future reference, please not that these github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
