### ISSUE TITLE
Question: what is the "double click" sample?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-examples#125]

**Comment by ericleich** [comment]
The Google Mobile Ads SDK supports 2 Google ad products: AdMob and [DoubleClick for Publishers](https://www.google.com/intl/en/doubleclick/publishers/welcome/) (DFP). DFP has a docset [here](https://developers.google.com/mobile-ads-sdk/docs/dfp/android/quick-start) that is similar to AdMob's. This GitHub repo hosts examples for both AdMob and DFP.

I'm assuming you're using AdMob, in which case I recommend sticking to the [AdMob docset](http://developers.google.com/admob/android/) and using the AdMob examples.
