### ISSUE TITLE
Need help with imported cordova project

### ISSUE THREAD

**Issue by huymc** [googleads/googleads-mobile-android-examples#128]
I created a project in cordova cli then imported it into android studio via gradle. How could i put admob into this project (in android studio)? Can someone help?

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

**With that said, to import Admob into an Android studio project, please start with our getting started documentation at https://developers.google.com/admob/android/quick-start.**

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
