### ISSUE TITLE
App  Crash： Error waiting for future:java.util.concurrent.TimeoutException 

### ISSUE THREAD

**Issue by pengyuan1990** [googleads/googleads-mobile-android-examples#130]
![image](https://user-images.githubusercontent.com/15941999/43113904-f0e6c70e-8f2e-11e8-9a5b-7bf4e940a3c5.png)    
SDK Version：
compile 'com.android.support:appcompat-v7:27.1.1'
compile 'com.google.android.gms:play-services-ads:15.0.1'

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
