### ISSUE TITLE
MediaView size in Native Ads Advanced.

### ISSUE THREAD

**Issue by Tecco** [googleads/googleads-mobile-android-examples#132]
Hello Google Ads Team,

The size of the MediaView in the sample layout file is 250 * 175.
But maybe it returned 250 * 150 Image and movie, and the iOS sample it is 250 * 150.

Which is right size?

**Comment by ericleich** [comment]
The reality is not every ad will come back with the same media aspect ratio. The way the sample does this is it picks a maximum width and height, and the ad that comes back fills one orientation and centers the other orientation. We could change the size to be more consistent with the iOS sample, but I wouldn't call either one "right". It kind of depends on what size your application can handle.

**Comment by Tecco** [comment]
OK, I got it. Thank you :)
