### ISSUE TITLE
Question : Integration with Paging Library

### ISSUE THREAD

**Issue by xcaEi** [googleads/googleads-mobile-android-examples#133]
Hello, 

In one of my projects, I have a list of items with ads in between, in similar manner to BannerRecyclerViewExample. I want to use the Paging Library from Architecture Components to handle the pagination of my list of items. 

You could easily handle the adding of ads at specific positions in the DataSource by adding ads when returning the items of a specific page. However I feel this goes against the nature of the DataSource.

I am wondering what implementation would be recommended ?

**Comment by kateile** [comment]
@xcaEi  Hi, I am thinking of doing the same, How you did it?
