### ISSUE TITLE
Failed to load for Native Ads Advanced on emulators

### ISSUE THREAD

**Issue by mkaflowski** [googleads/googleads-mobile-android-examples#134]
I get Failed to load ad: 0 for install native and Failed to load ad: 3 for content native on emulators. Ia have tested test app id and there is the same case. Its work on real device. How to fix that?

**Comment by stowy** [comment]
hi, is Google Play installed on the emulator? If it is not, this will explain why app install ads are not loading. For content ads, this may be related to a known issue where content ads won't load for non-published app ids. Are you testing with a published app ID?

**Comment by mkaflowski** [comment]
Hello. There is no Google Play. I wanted to test native ads on different resolutions and only Nexus emulator has GP. The app is published. Is tehere any way to load some test ads on emulators withou Google Play or install it?

**Comment by stowy** [comment]
Hi,

I have tested locally on an emulator with a test app ID from the public samples and am not able to reproduce. I receive content ads quite consistently.

Are you using the current public NativeAdvancedExample or your own implementation?

If you are using your own implementation, these github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details about how to reproduce the issue.
