### ISSUE TITLE
No AdChoices icon is shown in Native Advanced ad

### ISSUE THREAD

**Issue by tpom6oh** [googleads/googleads-mobile-android-examples#136]
![screenshot_1537430185](https://user-images.githubusercontent.com/9194227/45804438-c33d8180-bcc4-11e8-8d99-be7bae55b9c4.png)

I have the same issue in my production project and since the absence of AdChoices is violation of the rules I can't run the native ads in production.

**Comment by stowy** [comment]
Thanks for reporting, we are reviewing and will update with findings.

**Comment by stowy** [comment]
Hi, this appears to be an expected outcome if the ad being returned does not have an attribution property. The above ad is an AdMob test ad and as such does not have attribution. 

Have you reproduced this with your own ad unit ID? It shouldn't matter if it is configured to show test ads, it just needs to be your own ad unit.

To assist you further, can you please make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.
