### ISSUE TITLE
device stops loading ads on v9

### ISSUE THREAD

**Issue by goldstei** [googleads/googleads-mobile-android-examples#137]
We are seeing a strange issue with Android v9 devices getting into a state where ads stop loading. I say device, rather than app, because the problem appears in our app as well as `BannerExample` from `googleads-mobile-android-examples/kotlin/doubleclick/BannerExample`. If I restart the device, I get ads on both (for a while).

Below is the debug log output from `BannerExample` in working and not-working cases (on Pixel2). It looks to me that things start to change on the fifth request where the working app re-requests `https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html` and gets `200` (and goes on to make several more requests) while the not-working app requests `https://csi.gstatic.com/csi?s=gmob_sdk&v=3&os=9&sdk=28&device=Google%20Pixel%202&app=com.google.android.gms.example.bannerexample&is_lite_sdk=0&e=%2C318482077%2C318481074%2C318478496%2C318482457%2C318481055%2C&task.signals=s.67&task.webview-cookie=s.73&task.request-parcel=s.0&network_coarse=1&network_fine=13&task.server-transaction=f.60014&task.renderer=f.2&label.ttc=f.60096` and gets a `204` and stops, reporting `Ad failed to load : 2`

[adWorkingDebug.txt](https://github.com/googleads/googleads-mobile-android-examples/files/2415599/adWorkingDebug.txt)
[adNotWorkingDebug.txt](https://github.com/googleads/googleads-mobile-android-examples/files/2415603/adNotWorkingDebug.txt)

**Comment by ericleich** [comment]
Thanks for the report. We are actively investigating this.

**Comment by surajsingh1999** [comment]
Thnx sir

**Comment by stowy** [comment]
This issue has been resolved and is now obsolete.
