### ISSUE TITLE
Click native ads in window can not be open

### ISSUE THREAD

**Issue by NiaNingXue** [googleads/googleads-mobile-android-examples#138]
I use native ads in window view (WindowManager.addView), when click it, I can receive the click event, but the native ads don`t open google play or a web,
Does it the limit of the Admob sdk or the policy?

**Comment by stowy** [comment]
Hi, this could be a limitation of the AdMob SDK. However, these github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
