### ISSUE TITLE
Sample app (DFP/customrenderingexample) works on emulator but not phone

### ISSUE THREAD

**Issue by hunterhays** [googleads/googleads-mobile-android-examples#139]
This sample app (DFP/customrenderingexample) works for me on the emulator but not on my physical phone. The only code change I have made was to add my test device to the PublisherAdRequest builder. I tracked the session in Charles proxy and no ad request was even sent to DFP servers.

`10-08 15:48:10.537 4459-4459/com.google.example.gms.customrenderingexample I/Ads: Starting ad request.
    SDK version: afma-sdk-a-v13280019.12451000.1
    This request is sent from a test device.
    Webview loading for native ads.
10-08 15:48:10.607 4459-4459/com.google.example.gms.customrenderingexample I/Ads: Javascript has loaded for native ads.
10-08 15:48:20.644 4459-5561/com.google.example.gms.customrenderingexample W/Ads: There was a problem getting an ad response. ErrorCode: 0
10-08 15:48:20.652 4459-4459/com.google.example.gms.customrenderingexample W/Ads: Failed to load ad: 0`

**Comment by stowy** [comment]
Hi, thanks for contacting us.

I've tried this locally on my own device and did not face the same issues that you mentioned, I was able to load ads on my device with and without the test device hash.

Can you please post the details of your issue on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem. I recommend including the Charles logs you recorded, as well as including details of the device you are using - model, android version and Google play services version.
