### ISSUE TITLE
Load ads on recycleview with model class 

### ISSUE THREAD

**Issue by rddewan** [googleads/googleads-mobile-android-examples#141]
Hi how can i load banner ads on my recycle view
My arraylist loads data from sqlite  with model class

ArrayList<PostProperty> arrayListPost = new ArrayList<>();   
private ArrayList<Object> recyclerViewItems = new ArrayList<>();

thank you

**Comment by stowy** [comment]
Hi @rddewan thanks for contacting us.

Can I suggest that to start you please review the [BannerRecyclerView example sample code](https://github.com/googleads/googleads-mobile-android-examples/blob/master/java/advanced/BannerRecyclerViewExample/app/src/main/java/com/google/android/gms/example/bannerrecyclerviewexample/MainActivity.java#L109).

Following that if you have further questions please note that these github issues are for issues with the sample apps only, for support debugging or creating your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.
