### ISSUE TITLE
suddenly admob ad match rate goes down upto 10-15%.

### ISSUE THREAD

**Issue by mrdabhu** [googleads/googleads-mobile-android-examples#144]
I got so many installs on my app in short of time, than google admob ad stop loading...
i got so many network requests but i got just few impression like in 100 network request i got just 5-10 impressions. so now what i do???

**Comment by ericleich** [comment]
Hi there, this sounds like an issue particular to your account or implementation, not necessarily the examples themselves. There's not much info here to work off so I can't tell you if it's an SDK implementation issue or not. For SDK integration issues, we ask that you direct these questions to the [Google Mobile Ads SDK developer forum](https://groups.google.com/group/google-admob-ads-sdk). For general product support, [AdMob product forum](https://productforums.google.com/forum/#!forum/google-admob-help-forum) is the appropriate place to write in.
