### ISSUE TITLE
Caused by java.lang.IllegalStateException

### ISSUE THREAD

**Issue by noinlijin** [googleads/googleads-mobile-android-examples#150]
android os : 8.0.0   

info:  http://crashes.to/s/142e24f44a8    

```
Fatal Exception: java.lang.RuntimeExceptionUnable to start activity ComponentInfo{com.security.xvpn.z35kb/com.google.android.gms.ads.AdActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation Raw Text
--
  | android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2955)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)




```

Please fix this bug as soon as possible, we have more than 1000 users crashed

**Comment by stowy** [comment]
Hi, can you please confirm your build configuration? Do you have a sample app we can reproduce with? Need to know what version of the Ads SDK, target android SDK, build tools version, etc you are using so we can narrow down what issue you are facing.

Also, as a general note, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently and you will receive a faster response.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
