### ISSUE TITLE
There was a problem getting an ad response. ErrorCode: 0

### ISSUE THREAD

**Issue by andreabellitto** [googleads/googleads-mobile-android-examples#155]
I have this response on all devices even with mobile connection or wifi home ADSL connection.

My revenue went from 30$/day to 1$/day.

Attached are charles proxy report.

From what I can see it seems that google ads server give me always a 503 error response.
[charles_report.chls.zip](https://github.com/googleads/googleads-mobile-android-examples/files/2872270/charles_report.chls.zip)

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
