### ISSUE TITLE
No resource found error for `com.google.android.gms:play-services-ads:7.5.0` in android studio 1.3

### ISSUE THREAD

**Issue by amrut8winjit** [googleads/googleads-mobile-android-examples#17]
E:\Shared_Folder\Sample Projects and Libraries\googleads-mobile-android-examples-master\admob\NativeExample\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\7.5.0\res\drawable\common_signin_btn_icon_light.xml

    Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_icon_disabled_focus_light').

    E:\Shared_Folder\Sample Projects and Libraries\googleads-mobile-android-examples-master\admob\NativeExample\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\7.5.0\res\drawable\common_signin_btn_text_light.xml

    Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_text_disabled_focus_light').

    Error:Execution failed for task ':app:processDebugResources'.
    com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\ANDROID-DEV\AndroidStudioSDK\build-tools\22.0.0\aapt.exe'' finished with non-zero exit value 1

while using sample app for admob native example, above error is showing. I'm unable to edit the resource as well. What can be the solution for this? i have used latest version of play services ads 7.5.0. 

    compile 'com.google.android.gms:play-services-base:7.5.0'
    compile 'com.google.android.gms:play-services-ads:7.5.0'

Please help to resolve this problem.

**Comment by RedBrogdon** [comment]
What variant of Android Studio 1.3 are you using (beta, canary, etc.), and do you have this issue when building with the current stable release?

**Comment by CongBaDo** [comment]
You can update it to 
compile 'com.google.android.gms:play-services-base:7.8.0'
compile 'com.google.android.gms:play-services-ads:7.8.0'
to fix it.

**Comment by amrut8winjit** [comment]
I have now tried using 
    compile 'com.google.android.gms:play-services-base:7.8.0'
    compile 'com.google.android.gms:play-services-ads:7.8.0'
to fix it. But still Im getting below error:
    E:\Shared_Folder\Sample Projects and Libraries\googleads-mobile-android-examples-master\admob\NativeExample\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\7.8.0\res\drawable\common_signin_btn_icon_light.xml
    Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_icon_disabled_focus_light').
    E:\Shared_Folder\Sample Projects and Libraries\googleads-mobile-android-examples-master\admob\NativeExample\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\7.8.0\res\drawable\common_signin_btn_text_light.xml
    Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_text_disabled_focus_light').
    Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\ANDROID-DEV\AndroidStudioSDK\build-tools\23.0.0\aapt.exe'' finished with non-zero exit value 1

**Comment by amrut8winjit** [comment]
I was able to fix it using only this:

compile 'com.google.android.gms:play-services-ads:8.3.0'

instead of this :

compile 'com.google.android.gms:play-services-base:7.8.0'
compile 'com.google.android.gms:play-services-ads:7.8.0'

Thanks.
