### ISSUE TITLE
Banner ad pause/resume not documented

### ISSUE THREAD

**Issue by SzyQ** [googleads/googleads-mobile-android-examples#172]
Documentation for banner ad doesn't mention anything about pause/resume, is it still required?
https://developers.google.com/admob/android/banner

**Comment by stowy** [comment]
It is recommended but not necessarily required. It forwards the call to the [WebView](https://developer.android.com/reference/android/webkit/WebView.html#onPause()) so it is good practice to minimize resource usage.
