### ISSUE TITLE
Version 18.1.0 Fails on Android 4 devices

### ISSUE THREAD

**Issue by SzyQ** [googleads/googleads-mobile-android-examples#174]
Hey,

After updating to 'com.google.android.gms:play-services-ads:18.1.0' I started to see on Android 4.X devices VerifyError for both Banner and Interstitial ads.
Any clue what has changed and may cause such error?
java.lang.VerifyError: c/f/b/a/j/a/FJ
	at com.google.android.gms.internal.ads.zzdal.zzdt(zzdal.java:68)
	at com.google.android.gms.internal.ads.zzbet.zzaci(zzbet.java:206)
	at com.google.android.gms.internal.ads.zzclo.zza(zzclo.java:27)
	at com.google.android.gms.internal.ads.zzwu.zza(zzwu.java:123)
	at com.google.android.gms.ads.BaseAdView.loadAd(BaseAdView.java:15)

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
