### ISSUE TITLE
Crash in com.google.android.gms.ads.internal.webview.v.destroy on RewardedVideoAd and InterstitialAd

### ISSUE THREAD

**Issue by luohaoyang** [googleads/googleads-mobile-android-examples#185]
```

1 #00 pc 008a9fcc /system/app/WebViewGoogle/lib/arm/libwebviewchromium.so [armeabi-v7a]
--
2 java:
3 org.chromium.content.browser.webcontents.WebContentsImpl.getUrl(WebContentsImpl.java:277)
4 org.chromium.android_webview.AwContents.loadUrl(AwContents.java:1439)
5 org.chromium.android_webview.AwContents.loadUrl(AwContents.java:1325)
6 org.chromium.android_webview.AwContents.loadUrl(AwContents.java:1337)
7 com.android.webview.chromium.WebViewChromium.loadUrl(WebViewChromium.java:551)
8 android.webkit.WebView.loadUrl(WebView.java:859)
9 com.google.android.gms.ads.internal.webview.v.e(:com.google.android.gms.policy_ads_fdr_dynamite@20461003@20461003.264725060.264725060:1)
10 com.google.android.gms.ads.internal.webview.v.destroy(:com.google.android.gms.policy_ads_fdr_dynamite@20461003@20461003.264725060.264725060:7)
11 com.google.android.gms.ads.internal.webview.t.destroy(:com.google.android.gms.policy_ads_fdr_dynamite@20461003@20461003.264725060.264725060:10)
12 com.google.android.gms.ads.nonagon.ad.rewardedvideo.c.run(Unknown Source)
13 android.os.Handler.handleCallback(Handler.java:739)
14 android.os.Handler.dispatchMessage(Handler.java:95)
15 vw.a(:com.google.android.gms.policy_ads_fdr_dynamite@20461003@20461003.264725060.264725060)
16 com.google.android.gms.ads.internal.util.g.a(:com.google.android.gms.policy_ads_fdr_dynamite@20461003@20461003.264725060.264725060:1)
17 vw.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@20461003@20461003.264725060.264725060)
18 android.os.Looper.loop(Looper.java:160)
19 android.app.ActivityThread.main(ActivityThread.java:5541)
20 java.lang.reflect.Method.invoke(Native Method)
21 java.lang.reflect.Method.invoke(Method.java:372)
22 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
23 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

```
This crash started appearing on my app's crash reports in Aug 1, and sooner become largest one（about 22000 users/day）.  I have study this crash for weeks, it seems that it happened when the RewardedVideoAd or InterstitialAd Object is recycled by GC, but I can't reproduce locally.
![image](https://user-images.githubusercontent.com/12524265/63937645-6c742680-ca95-11e9-9ad5-444986e9b174.png)

And then I find a similar crash by not exactly same: https://github.com/googleads/googleads-mobile-android-examples/issues/170. Lots of developers have reported this crash from May to July, and in the last comment  I find you fix this bug in about Aug 1.

Is it possible my crash appeared  because of you fixed last crash? This crash appeared on every version of my app, and I didn't update Admob or GMS SDK for a long time.   If you have any solution or need more information，please contact me at once, thanks.

My firebase version: **com.google.firebase:firebase-ads:17.1.2**

**Comment by hoangtunho2611** [comment]
I have this error just like you. and waitting for the final answer.

**Comment by luohaoyang** [comment]
@stowy This crash has seriously impact our DAU, please help.

**Comment by stowy** [comment]
We're working on this internally with the WebView team to resolve this issue. These issues are very hard to track down especially as they often relate to old versions of WebView. 

You will get more immediate support if you file an issue in the support forum https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help file an issue for this crash.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
