### ISSUE TITLE
Eclipse examples not found !

### ISSUE THREAD

**Issue by github8866** [googleads/googleads-mobile-android-examples#19]
I don't find any examples  for Eclipse

**Comment by RedBrogdon** [comment]
[Android Studio](https://developer.android.com/sdk/index.html) is the official IDE for Android development, so we build most of our examples as Android Studio projects. The classes and resources can be used in either IDE, though, and you can use the [gradle plugins](https://gradle.org/eclipse/) for Eclipse to build the project as well.
