### ISSUE TITLE
Rewarded ad video pause issue

### ISSUE THREAD

**Issue by 5ALEKSEY** [googleads/googleads-mobile-android-examples#191]
There are two issues with video pause state:
1) Rewarded ad video still continue playing if user put application in background (_~2 secs until video finish_).
2) Rewarded ad video still continue playing if user try to close video via X button (_~2 secs until video finish_).

It's very strange. I mean about '_2 secs until video finish_' state and it's occurs unpleasant bugs :(

P.S. i tested on your sample application too. I can share video if you want

**Comment by stowy** [comment]
Can you please file an issue in the support forum https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help file an issue for this crash.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for these SDK specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
