### ISSUE TITLE
Google Ads loading in PublisherAdview

### ISSUE THREAD

**Issue by sanamdongol** [googleads/googleads-mobile-android-examples#197]
I am having issue with PublisherAdview. Whenever  I use my publisher AdUnit Id it loads google ads even if i use PublisherAdview.

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on
our support forum at
https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android -
they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps
only, as more in depth support for your specific issues is handled by our
support team on the forum.

When posting to the forum, please also provide specific details including
any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details
including which sample app and specific steps to reproduce the issue.

Regards

Sam
