### ISSUE TITLE
Adaptive example - How to know if showing an adaptive ad?

### ISSUE THREAD

**Issue by bickster** [googleads/googleads-mobile-android-examples#201]
Hi,

In the Adaptive example, how do you know if you are showing an adaptive banner ad or a normal banner ad?

Thanks,
Chris

**Comment by stowy** [comment]
Hi @bickster - the ad size used in the adaptive example is an adaptive ad size. See the [developer guide](https://developers.google.com/admob/android/banner/adaptive) for more details.

The banner may occasionally fill with a smaller size, eg 320x50, but the banner will still be the full adaptive size and the ad will be centered in the view.

Whenever you use an ad size returned from an adaptive ad size API (eg `AdSize. getCurrentOrientationAnchoredAdaptiveBannerAdSize`) you are showing an adaptive banner, regardless of the size of the ad returned.
