### ISSUE TITLE
Ads not showing using my Ads units during 

### ISSUE THREAD

**Issue by chikason** [googleads/googleads-mobile-android-examples#207]
I have published my application on play store on a test mode/release.
I linked my admob App account with the App on play store but the ads is not  showing and it was showing when i was using ads test units .
So must i release it in production before it will show using my ads units.

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
