### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by BulatMukhutdin** [googleads/googleads-mobile-android-examples#214]
When using the latest test ads id ```ca-app-pub-3940256099942544/6300978111``` and removing ```addTestDevice()``` an ads background become black.
![Screenshot_20200311-123123](https://user-images.githubusercontent.com/57901150/76402412-76f07080-6394-11ea-8bb8-d981bbedc224.png)

**Comment by stowy** [comment]
This is expected for the test ad, it's the creative's way of filling unused space. This does not occur with other (non-test) creatives, try using your own ad units with your device [configured as a test device](https://developers.google.com/admob/android/test-ads#add_your_test_device).
