### ISSUE TITLE
Need Sample to load ads when using android paging library 

### ISSUE THREAD

**Issue by adhavanj** [googleads/googleads-mobile-android-examples#222]
It looks like there is no proper sample app that explains how to add native ads while using the android paging library.

**Comment by stowy** [comment]
Hi @adhavanj we don't have examples to cover use of other libraries, however there is [this codelab](https://codelabs.developers.google.com/codelabs/admob-native-advanced-feed-android) for using a recyclerview that you may find useful. You may ignore the firebase component if not needed.
