### ISSUE TITLE
Is it legal to add banner ads into recyclerview?

### ISSUE THREAD

**Issue by gordonfreemanix** [googleads/googleads-mobile-android-examples#227]
I just want to know. some people say this is wrong and we they say we should use native ads. Is this true?

**Comment by stowy** [comment]
No, you are allowed to use banner ads in a recycler view. We demonstrate this in [our sample](https://github.com/googleads/googleads-mobile-android-examples/tree/master/java/advanced/BannerRecyclerViewExample).

**Comment by gordonfreemanix** [comment]
@stowy I just wanted to be sure. Reddit and Stackoverflow also said it caused false clicks. instead it is now said that google should use native ads? is this true?

**Comment by stowy** [comment]
That's not something I've heard myself. I think it could be possible depending on the implementation. I would recommend reviewing [our guidance on this](https://support.google.com/admob/answer/2936217?hl=en&ref_topic=2936214).

**Comment by gordonfreemanix** [comment]
> That's not something I've heard myself. I think it could be possible depending on the implementation. I would recommend reviewing [our guidance on this](https://support.google.com/admob/answer/2936217?hl=en&ref_topic=2936214).
@stowy 
Refreshing ads
Does this cause an error? because in recyclerview, ads will be refreshed in less than 60 seconds

**Comment by stowy** [comment]
No, you are free to load ads as needed. If you start loading too many ads (eg automatic retry on error) then you will start getting load errors.
