### ISSUE TITLE
interstitial  in both activity and fragment

### ISSUE THREAD

**Issue by pawaom** [googleads/googleads-mobile-android-examples#238]
interstitial in both activity and fragment

I have a an Activity and a Fragment(which is part of same activity, and is also used on other activities )

Both have separate functionality

There are few buttons in Activity , when they are clicked we go to next Activity and similarly there are different buttons in fragment  , which  when they are clicked we go to next Activity

can we show interstitial in between , when user goes from one activity to another and from one fragment to another

 **Fragment(is part of same activity)**

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
