### ISSUE TITLE
AdActivity is not supported display cutout

### ISSUE THREAD

**Issue by kjt0429** [googleads/googleads-mobile-android-examples#241]
[Test case]
device: Galaxy fold (Android os 10.0)
product: Admob Unity package
api: Reward Video

Hello,

i have a problem. When i call API RewardVideo.show(), letterbox area is empty.
(Not filled black. so my users can see the background activity, and this looks  strange.)

Looking at the activity stack, RewardVideo is exposed to the new activity(com.google.android.gms.ads.AdActivity), not as Dialog.

Could you support display cutout 'AdActivity'?

https://developer.android.com/guide/topics/display-cutout

**Comment by stowy** [comment]
Hi @kjt0429  thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
