### ISSUE TITLE
Ad failed to load : 0 on compileSdkVersion 30

### ISSUE THREAD

**Issue by Lovig90** [googleads/googleads-mobile-android-examples#242]
Unable to show native ads when compile sdk version is set to 30. Tested on Google Pixel 3a with Android 11 beta1.

**Comment by stowy** [comment]
Hi @Lovig90, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
