### ISSUE TITLE
requestFeature() must be called before adding content 

### ISSUE THREAD

**Issue by orlytops** [googleads/googleads-mobile-android-examples#29]
I got this error and I don't know what causes this. Can you help me wit this error? 

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample.app/com.google.android.gms.ads.AdActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2658) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723) at android.app.ActivityThread.access$900(ActivityThread.java:172) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:145) at android.app.ActivityThread.main(ActivityThread.java:5832) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:352) at android.app.Activity.requestWindowFeature(Activity.java:3759) at com.google.android.gms.ads.internal.overlay.ab.a(:com.google.android.gms.DynamiteModulesA:279) at com.google.android.gms.ads.internal.overlay.client.c.onTransact(:com.google.android.gms.DynamiteModulesA:58) at android.os.Binder.transact(Binder.java:380) at com.google.android.gms.internal.zzfk$zza$zza.onCreate(Unknown Source) at com.google.android.gms.ads.AdActivity.onCreate(Unknown Source) at android.app.Activity.performCreate(Activity.java:6221) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)  at android.app.ActivityThread.access$900(ActivityThread.java:172)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:145)  at android.app.ActivityThread.main(ActivityThread.java:5832)  at java.lang.reflect.Method.invoke(Native Method)  at java.lang.reflect.Method.invoke(Method.java:372)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

Here's my XML code
` <com.google.android.gms.ads.AdView
    android:id="@+id/ad_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_centerHorizontal="true"
    android:layout_alignParentBottom="true"
    ads:adSize="BANNER"
    ads:adUnitId="@string/banner_ad_unit_id" />`

an declared it on onFinishInflate of my custom view

 `@Override
protected void onFinishInflate() {
    super.onFinishInflate();
   mAdView = (AdView) findViewById(R.id.ad_view);
   AdRequest adRequest = new AdRequest.Builder()
            .build();
   adView.loadAd(adRequest);
}`

**Comment by ericleich** [comment]
What version of Google Play services are you compiling into your app? Any chance its less than Google Play services 4.4?

**Comment by rampara** [comment]
Closing issue due to its age. If this issue still persists for you, please re-open it.

**Comment by AlexMisiulia** [comment]
Just if someone faced the same issue in 2020. As mentioned [here](https://groups.google.com/forum/#!topic/google-admob-ads-sdk/lkhSvL78HO4) my problem was that I use [IMMLeaks](https://gist.github.com/pyricau/4df64341cc978a7de414) helper class which cause this exception. My fast solution was to remove IMMLeaks from my source code. I decided that crashes are more fatal to my app than memory leaks :)
