### ISSUE TITLE
Missing manfiest meta data (sic)

### ISSUE THREAD

**Issue by amyquispe** [googleads/googleads-mobile-android-examples#3]
To make sure the AdMob Ads are clickable please add the following line to the manifest file of your unity project under assets->plugin->android->AndroidManifest.xml

<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />

so Unity will forward clicks on the admob view to open the Add activity :)

This line must be added inside the <application> tag

Also make sure there is not another line with false value :)

Originally reported by mahmoudfayez on October 28, 2013

**Comment by natsihitt** [comment]
s
