### ISSUE TITLE
Performance issue on NativeExpressAdView 

### ISSUE THREAD

**Issue by longbkiter07** [googleads/googleads-mobile-android-examples#30]
I've got performance issue when rendering NativeExpressAdView.
Here are some informations:
Version: `com.google.firebase:firebase-ads:9.0.2`
I used this sample app: https://github.com/googleads/googleads-mobile-android-examples/tree/master/admob/NativeExpressExample and change a bit to log the render time:

```
public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    NativeExpressAdView adView = (NativeExpressAdView) findViewById(R.id.adView);
    long beginTime = System.currentTimeMillis();
    adView.loadAd(new AdRequest.Builder().build());
    long endTime = System.currentTimeMillis();
    Log.e(getClass().getSimpleName(), "loadAds time:" + (endTime - beginTime));
  }
}
```

The logcat says the time when `adView.loadAd(new AdRequest.Builder().build());` runs is 400-500ms, it's not acceptable.
Please help me to fix this issue. Thanks

**Comment by clockbyte** [comment]
+1 the same speed for me...

**Comment by RedBrogdon** [comment]
Hmm. This call:

        adView.loadAd(new AdRequest.Builder().build());

includes both loading and rendering time, so it's dependent on network conditions. On Wifi, though, I would expect it to be faster than 500ms. Do you see this speed on every request, or just the first?

**Comment by longbkiter07** [comment]
I don't think so. I'm using wifi thats very high speed. When I try to turn off wifi and try to load the ad, the issue still occurs. Actually, we should not do it on main thread (NetworkOnMainThreadException will be thrown), so I'm sure that is the rendering issue.

**Comment by gholadr** [comment]
+1 yes, we see this issue on high speed connections. first time only.

**Comment by nakamin** [comment]
@longbkiter07 I don't think this test is very accurate. First of all, as @RedBrogdon said, the load speed will depend on the network connection. Secondly, if I'm not mistaken, your test isn't even measuring the ad load time. The `loadAd()` method is asynchronous [(see docs)](https://developers.google.com/android/reference/com/google/android/gms/ads/NativeExpressAdView.html#loadAd(com.google.android.gms.ads.AdRequest)), i.e it kicks the work off to another thread and continues execution. You need to set an [`AdListener`](https://developers.google.com/android/reference/com/google/android/gms/ads/AdListener) on your `NaitveExpressAd` using the [`setAdListener()`](https://developers.google.com/android/reference/com/google/android/gms/ads/NativeExpressAdView.html#setAdListener(com.google.android.gms.ads.AdListener)) method, and then take your final time measurement in the [`onAdLoaded()`](https://developers.google.com/android/reference/com/google/android/gms/ads/AdListener.html#onAdLoaded()) method of the listener. However, I can't argue that ad loading isn't slow, I'm experiencing the same problem as you in my own app.

**Comment by cgpllx** [comment]
runs is 400-500ms

**Comment by ericleich** [comment]
Marking this as obsolete as Native Express is now deprecated. Further, any issues with other formats experiencing similar delays are a part of the Google Mobile Ads SDK behavior and not the examples themselves, so this isn't the right venue for this issue.

The slow ad loading itself is acknowledged, and is being addressed as part of a larger internal cleanup of the SDK. I'm unable to provide a timeline on when that will drop though. The target keeps moving.

For further updates and inquiries on this issue, please reach out to the [Google Mobile Ads SDK developer forum](https://groups.google.com/group/google-admob-ads-sdk).
