### ISSUE TITLE
Admob Test Ads shows black screen ( Banner + Interstitial )

### ISSUE THREAD

**Issue by Norman191** [googleads/googleads-mobile-android-examples#311]
my app loads ads and shows only black screen.

I use test ads and with ad listener they loaded successfully, but only display black screen ads, also they are clickable.

Using the latest SDK :
 **com.google.android.gms:play-services-ads:19.7.0**

Device : 
**Infinix Android V 5.1**

they were working fine a few days ago, but almost 5 days now, are only displaying black screen.

Any help please ?

**### UPDATE :** 
working fine in Android 4.2.2, so i guess the problem happens in Android 5.1 only.

**Comment by ericleich** [comment]
Sorry for the delay, this turned out to be an issue with AdMob Campaigns that the test ads were based off of. I would expect it to work again for you on Android 5.1.
