### ISSUE TITLE
Intertitial and Reward in Kotlin v.19.7.0?

### ISSUE THREAD

**Issue by danieldz7** [googleads/googleads-mobile-android-examples#314]
Please, when will any of the contributors update the kotlin v.19.7.0 versions? The documentation does not help at all, super complicated and difficult to migrate.

**Comment by ericleich** [comment]
@danieldz7 Kotlin samples have been updated in https://github.com/googleads/googleads-mobile-android-examples/commit/c32064f326efacc3c19273895833f3b2c68ae032
