### ISSUE TITLE
Banner RecyclerView Example

### ISSUE THREAD

**Issue by midUI108** [googleads/googleads-mobile-android-examples#316]
Hi, why is the implementation of ads in RecyclerView shown here, but when sending the app to Google Play, it is rejected because several ads are banned on the same page?

**Comment by ericleich** [comment]
The example is there to demonstrate how to put ads in some kind of scrolling view, a common practice among apps with feeds. To work around the play rejection, you may consider changing the frequency at which ads display. In the sample, that would be [here](https://github.com/googleads/googleads-mobile-android-examples/blob/master/java/advanced/BannerRecyclerViewExample/app/src/main/java/com/google/android/gms/example/bannerrecyclerviewexample/MainActivity.java#L35).

**Comment by midUI108** [comment]
Hi, in our implementation, the simultaneous display of several ads is excluded, the verifiers complain about the presence of several ads in the scrollable list, that is, the ad is shown, the verifiers scroll through the list, and after a few elements there is a second ad block, when the previous one is already hidden. Can we refer to your answer when analyzing this situation in the Google console? Thank you..

![image](https://user-images.githubusercontent.com/80316573/111213684-7499a580-85ea-11eb-82cf-25e954563088.png)

**Comment by ericleich** [comment]
@midUI108 Feel free to refer the play policy team to this discussion, but it's ultimately their call. This policy of 1 ad per page may be specific to the families ads program. Certainly, many feed-style apps have multiple ads as you scroll through. If this is still blocking you, you may consider moving the ad outside of the recyclerview, and placing it in a static position at the top or bottom of the screen.

In the meantime, I'm going to close this issue as we will still want the recycler view example to show the in-recyclerview feed use case that is common for apps outside of the family program.
