### ISSUE TITLE
Failed to load ad

### ISSUE THREAD

**Issue by petrachenicolaedaniel** [googleads/googleads-mobile-android-examples#32]
Hello, tried the sample app with my app id but this happens 
07-11 11:49:27.163 1485-1485/com.google.example.gms.nativeexample W/Ads: Failed to load ad: 0
Also tried to integrate it in my app release version but still the same error.

**Comment by ericleich** [comment]
This might be a bug in the SDK that we've been recently investigating. To verify it's the same problem:

- Any chance the device you're testing on doesn't have the Google Play services apk (or it's older than what you're compiling with)?
- If you change the gradle target to `compile 'com.google.android.gms:play-services-ads:8.4.0'`, then do ads load?

**Comment by petrachenicolaedaniel** [comment]
Nope, testing on Galaxy S6 with android 6.0.1. Tried to downgrade to 8.4.0 but no luck, still the same error.

**Comment by serralove** [comment]
me too how fix it.
i'm using this version
   compile 'com.google.android.gms:play-services-ads:8.1.0'

**Comment by ericleich** [comment]
@petrachenicolaedaniel what version of Google Play services do you have installed? You can check this by going to Settings -> Apps -> Google Play services and there should be a version on there.

**Comment by petrachenicolaedaniel** [comment]
@ericleich Version 9.2.56(440-124593566)

**Comment by ericleich** [comment]
Hmm, this must be different than the bug we've been seeing. What I'm referring to is a situation where there are several "Google Play services is missing" logs followed by a "Failed to connect to remote ad service", leading to the ad failure. This wouldn't apply to you as your device has the latest play services.

Either way, if this is a problem it's going to be with the SDK itself and not the sample app. This is a better question for the [SDK support group](groups.google.com/group/google-admob-ads-sdk), and I'd recommending providing more logs before this that can help scope the problem.

**Comment by serralove** [comment]
you can  use demo key. it's works.i tried.
