### ISSUE TITLE
Question: about reward ads, is it possible to get whether they were granted even after app was reset

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-examples#35]
Suppose the user has got the reward, and later the app was reset or was installed on another device the user has, is it possible to get the state of the reward, so that it won't be possible to get it again (and also give it to the user) ? 

I'm talking about this topic:
- https://firebase.google.com/docs/admob/android/rewarded-video?utm_campaign=admob_series_androidvideoguide_072816&utm_source=gdev&utm_medium=yt-desc
- https://www.youtube.com/watch?v=TIiY1VIIQwg&feature=em-subs_digest-wl
- https://github.com/googleads/googleads-mobile-android-examples/tree/master/admob/RewardedVideoExample

**Comment by rampara** [comment]
At this time, AdMob does not support the ability to check if a user was previously rewarded. Publishers who require this functionality will have to maintain the state of the reward themselves

**Comment by AndroidDeveloperLB** [comment]
So I need to have a server with DB and add identification mechanism (and
permissions) to the app, just for this?

Please consider adding this. It could also be nice to be able to grant the
reward on other cases (for example filling a survey or something).

**Comment by AndroidDeveloperLB** [comment]
Is there any forum or website where I can provide feedback (issues and
suggestions) for the ads sdk ?

**Comment by rampara** [comment]
The Google Mobile Ads SDK [forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) would be the best place for that.

**Comment by AndroidDeveloperLB** [comment]
ok, here:

https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/android/YHY81Bhlpd4

Please do consider adding this.
