### ISSUE TITLE
Failed to Load native ad: 0

### ISSUE THREAD

**Issue by davidgcalle** [googleads/googleads-mobile-android-examples#38]
Hi, I been trying to add native advanced adds to a recyclerview taking this project as an example and being successful with the "Install ads", but unable to do it with the "Content Ads", even on the "NativeAdvancedExample" app, got the same error. 

Any Ideas?

**Comment by stateInstance** [comment]
I have got the same problem with you ,did you solve the problem? or have any ideas ? thank you!

**Comment by temrich** [comment]
What error(s) are you getting? Are you using the NativeExpressRecyclerView example app (but replacing Native Express ads with content ads)?

**Comment by temrich** [comment]
Was able to reproduce the "failed to load native ad" error with the Native Advanced example. Will take a look to see what is going on and will get back to. Thank you for reporting this issue!

**Comment by davidgcalle** [comment]
@temrich Hi,  no I'm using the "NativeAdvancedExample" demo,  https://github.com/googleads/googleads-mobile-android-examples/tree/master/admob/NativeAdvancedExample . 

This demo uses both,  install and content ads.  Thanks for your response

**Comment by temrich** [comment]
Hi, I was able to reproduce this error using the Android Emulator, but was not able to reproduce on an actual device. 

I also used the NativeAdvancedExample app. Can you please let me know if you are able to reproduce on an actual device?

**Comment by davidgcalle** [comment]
@temrich hi, sorry for the late response, wasn't able comment don't know why, the answer is yes, I'm almost always testing with real devices, on this issue I was testing on a Nexus 6 and a Moto G 3th, and on both had the same issue, sometimes it works, but most of them don't.

**Comment by temrich** [comment]
Hi David,

I tested the AdMob Native Advanced example app on both a Nexus 6 (6.0.1) and Moto G (4.4.4) and was able to successfully get app install and content ads to load. Are you using the test ad unit IDs in the example or are you using your own? Any chance you can provide a logcat where you are able to reproduce the issue?

**Comment by n4554** [comment]
i have same problem on  Android Emulator and LG device . 
the error on Emulator:
 Requires 10084000 but found 6774480
W/Ads: Received error HTTP response code: 403
W/Ads: There was a problem getting an ad response. ErrorCode: 0
W/Ads: Failed to load ad: 0
W/EGL_emulation: eglSurfaceAttrib not implemented
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7feb80987e00, error=EGL_SUCCESS

**Comment by ericleich** [comment]
`W/Ads: Received error HTTP response code: 403` indicates that the server rejected the ad request. One reason for this is the ad unit ID is either not a native ads ad unit ID, or the account it's coming from is not enabled for native ads advanced.

I just checked and the Android guide is incorrectly pointing to an iOS ad unit. But the sample app has a working Android ad unit. So can you try with `ca-app-pub-3940256099942544/2247696110` and see if that resolves the issue?

**Comment by n4554** [comment]
@ericleich Thanks for great response . i tast RewardedVideo Ads in androidstudio and use this ad unit ID  `ca-app-pub-5920324855307233/4458481507` after read your comment test that but . the problem is not solve . 
the error is : 
`02-01 22:00:57.230 2169-2169/com.google.ads.rewardedvideoexample I/Ads: Starting ad request.
02-01 22:00:59.800 2169-4169/com.google.ads.rewardedvideoexample W/Ads: Received error HTTP response code: 403
02-01 22:00:59.800 2169-4169/com.google.ads.rewardedvideoexample W/Ads: There was a problem getting an ad response. ErrorCode: 0
02-01 22:00:59.800 2169-2169/com.google.ads.rewardedvideoexample W/Ads: Failed to load ad: 0
02-01 22:00:59.860 2169-2316/com.google.ads.rewardedvideoexample W/EGL_emulation: eglSurfaceAttrib not implemented
02-01 22:00:59.860 2169-2316/com.google.ads.rewardedvideoexample W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7f625a7d03c0, error=EGL_SUCCESS`

**Comment by ericleich** [comment]
Hey @n4554,

Thanks for the logs. I can see now that you're trying to do rewarded video, not native ads like the other folks on this issue. So the ad unit I recommended is not applicable.

There are 3 things you'll need to do to get rewarded video:
1) Your ad unit, `ca-app-pub-5920324855307233/4458481507` appears to be an "Interstitial" ad unit on an "iOS" app in the front-end for your account. You'll want to create a different ad unit in your Android app with type "Rewarded Interstitial".
2) AdMob only supports rewarded video via mediation right now, so to get ads you would need to configure another ad network library to serve ads. You can check [here](https://firebase.google.com/docs/admob/android/mediation-networks) to see which ad networks support rewarded video and [here](https://firebase.google.com/docs/admob/android/rewarded-video#add_network_adapters_and_sdks) for general instructions on how to get that ad network SDK + adapter library into your project. When you download an adapter, there should also be a README explaining some specific steps for that network. 
3) Once you integrate the 3rd party adapter and SDK into your app, modify your ad unit's mediation settings to add the network you integrated. You'll need to supply credentials from that network (which means having an account with them and creating an ad unit on their account).

This may all seem overwhelming if you haven't done it before. If the rewarded video format isn't applicable for your app (i.e. you don't have an incentive for the user for watching an ad), you may choose to implement regular [Interstitial Ads](https://firebase.google.com/docs/admob/android/interstitial) instead. AdMob does serve interstitial ads directly, so the steps are much more straightforward. Also, the [Interstitial Example](https://github.com/googleads/googleads-mobile-android-examples/releases) will run out of the box if you want to test it out.

**Comment by n4554** [comment]
@ericleich
 Thanks again  for your guidance .

**Comment by ericleich** [comment]
No problem, let me know if you have more questions.

**Comment by adnanali282** [comment]
Native advance ads not loading by change their ads id with their own id, any idea?
