### ISSUE TITLE
Successful display of advertising, but click on the ad did not respond

### ISSUE THREAD

**Issue by xiaoer521** [googleads/googleads-mobile-android-examples#39]
I do is the lock screen applications, and multi process related。

Thank you

**Comment by temrich** [comment]
Which example app are you referring to?

**Comment by artwl** [comment]
same question

**Comment by stowy** [comment]
Hi @artwl, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our support forum at https://groups.google.com/forum/#!forum/google-admob-ads-sdk - they will be able to help debug your issue with you efficiently.  If you have a specific issue with a sample app, please provide detail as to how to reproduce the issue.
