### ISSUE TITLE
Sometimes crashes with java.lang.IllegalStateException:

### ISSUE THREAD

**Issue by amyquispe** [googleads/googleads-mobile-android-examples#4]
__Please describe the Google AdMob Ads Android SDK bug you're experiencing.
If
applicable, please provide all of the following:__

__- SDK Version__
6.4.1

__- Complete description of the bug, including the expected and actual output__

Sometimes I got this crash:

E/AndroidRuntime(30551): FATAL EXCEPTION: main
E/AndroidRuntime(30551): java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
E/AndroidRuntime(30551): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:3506)
E/AndroidRuntime(30551): 	at android.view.ViewGroup.addView(ViewGroup.java:3377)
E/AndroidRuntime(30551): 	at android.view.ViewGroup.addView(ViewGroup.java:3322)
E/AndroidRuntime(30551): 	at android.view.ViewGroup.addView(ViewGroup.java:3298)
E/AndroidRuntime(30551): 	at com.google.ads.internal.d.a(SourceFile:1025)
E/AndroidRuntime(30551): 	at com.google.ads.internal.d.a(SourceFile:696)
E/AndroidRuntime(30551): 	at com.google.ads.e$8.run(SourceFile:445)
E/AndroidRuntime(30551): 	at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime(30551): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(30551): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(30551): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(30551): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(30551): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(30551): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime(30551): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime(30551): 	at dalvik.system.NativeStart.main(Native Method)

Originally reported by g.iuculano on October 31, 2013

**Comment by rampara** [comment]
Closing issue as this crash is reproducible on the latest version of the Google Mobile Ads SDK. If this issue still persists for you, please re-open it.
