### ISSUE TITLE
Leaky leaky

### ISSUE THREAD

**Issue by figengungor** [googleads/googleads-mobile-android-examples#40]
What is it that leaks the activity?

![device-2016-11-28-000352](https://cloud.githubusercontent.com/assets/3411015/20652235/18a709aa-b4fe-11e6-8d35-a776d0f3af64.png)

**Comment by temrich** [comment]
Hi, which version of firebase-ads are you using in your app's build.gradle file? Which version of Android and which device?

Try using the latest version:
compile 'com.google.firebase:firebase-ads:9.8.0'

**Comment by figengungor** [comment]
Hi @temrich,

I was using latest version  `com.google.firebase:firebase-ads:10.0.0` when I opened the issue. Now, the latest version is `10.0.1` and I tested with that one, too. However, it still leaks.

My Android version is 6.0.1 and my device is LG G5.

Thanks for caring.

**Comment by temrich** [comment]
Are you able to reproduce this leak with any of our sample apps?
What steps are you taking to reproduce the leak?

**Comment by figengungor** [comment]
1. Cloned your BannerExample.
2. Added LeakCanary as dependency:

```
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'
```
3. Added a CustomApp class to the sample to use LeakCanary:

```
public class CustomApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        LeakCanary.install(this);
    }
}

```

4. Changed app name in AndroidManifest:

 ```
<application
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        android:name=".CustomApp">
```

5. Run the sample app and then exit with back key. (If you can't see at first, please try to open and exit once more)

 LeakCanary finds a memory leak like in the screen shot.

**Comment by temrich** [comment]
Hi,
Thank you for the steps. Do you still see a leak if you add a banner ad to your own app?
If you do, then it could potentially be an SDK issue and I would recommend reporting it on our Mobile Ads Developer forum (https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android).
