### ISSUE TITLE
onRewardedVideoAdFailedToLoad, error code is 3

### ISSUE THREAD

**Issue by huyongli** [googleads/googleads-mobile-android-examples#42]
I use com.google.android.gms:play-services-ads:9.4.0

**Comment by temrich** [comment]
Hi,
Are you able to reproduce this issue with our rewarded video sample app? Please ensure you are inserting a valid ad unit ID into the rewarded video sample.

Also, these guides go into more detail about setting up rewarded video ads in your app:
https://firebase.google.com/docs/admob/android/rewarded-video
https://firebase.google.com/docs/admob/android/rewarded-video-adapters

**Comment by charlag** [comment]
I am experiencing the same issue with sample code. Does it require any additional configuration?

**Comment by miannoumanshah** [comment]
i am experiencing the same issue can u please explain becouse i do the same thing in sample

**Comment by stowy** [comment]
Hi, the Error code: 3 or [ERROR_CODE_NO_FILL](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_NO_FILL) simply means that ad request was successful but there are no ads to be served. One way to resolve this is to [mediate to more third-party ad networks](https://firebase.google.com/docs/admob/android/mediation).

This doesn't imply any error in your code and if you [test using test ads](https://developers.google.com/admob/android/test-ads) (eg add your device as a test device) you should see ads.
