### ISSUE TITLE
Received error HTTP response code: 403

### ISSUE THREAD

**Issue by captain-miao** [googleads/googleads-mobile-android-examples#44]
````
Ads: Starting ad request.
Ads: Received error HTTP response code: 403
Ads: There was a problem getting an ad response. ErrorCode: 0
Ads: Failed to load ad: 0
```
If use demo of AD_UNIT_ID = "ca-app-pub-2645501099195946/6426435425", it's success.
```
Ads: Starting ad request.
Ads: Ad finished loading.
```

I don't know why.

**Comment by captain-miao** [comment]
it's ok,by owner's ad-id.

**Comment by SherlockOy** [comment]
@captain-miao What do you mean by owner's ad-id？Also came into the problem. (Reply in Chinese If I 'm not mistaken.

**Comment by SherlockOy** [comment]
@captain-miao  What do you mean by owner's ad-id？Also came into the problem. (You can also reply in Chinese If I 'm not mistaken.

**Comment by captain-miao** [comment]
@SherlockOy 使用Google Play主账号对应的谷歌广告ID

**Comment by SherlockOy** [comment]
@captain-miao 我后来问了Google的相关人员，答复是Google Play Service框架的问题，国内ROM基本都剔除掉了，所以不行，目前似乎无解

**Comment by captain-miao** [comment]
@SherlockOy 是部分手机上出现吗？这个很好验证，你使用Nexus 或者 三星的手机验证下
