### ISSUE TITLE
Unable to run instrumental test after Google ads dependency implementation.

### ISSUE THREAD

**Issue by RobGas1** [googleads/googleads-mobile-android-examples#448]
I couldn't run instrumental(UI) tests after Google ads dependency implementation. The runner crashed every time; I tried to implement it to the dummy project because initially, I thought that the problem was in my project, but it seemed not I got the same result on the dummy project, So merely my instrumental tests didn't run. I have inspected the google ads dependency and spotted that the root cause was google ads-lite which is used by the google ads library. I tried a few variants such as change runner, run it on x86, x64 platforms, change lib version, change Gradle version, change AGP version. But I can't find a solution.
 
Steps to reproduce
1. Create a dummy project(runner: "androidx.test.runner.AndroidJUnitRunner")
2. Run an instrumental test to make sure that was passed successfully
3. Implement com.google.android.gms:play-services-ads: 20.5.0(or latest version)
4. Run an instrumental test it should be stuck because of the runner crash

**Comment by hasenrhaem** [comment]
ا

**Comment by mwshubham** [comment]
+1 facing the same issue

Any help here. Have logged similar here: https://support.google.com/admob/thread/280811702?hl=en&sjid=3786698704867083663-AP

**Comment by NVentimiglia** [comment]
Do you have an error log? please post.

**Comment by mwshubham** [comment]
Thanks @NVentimiglia for your reply. 
In my case the below `meta` was present in module higher in hierarchy than the module where I was running the instrumented test. This results in application to build properly due to manifest merging, however, build failure when we are running instrumented test in library module.

```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="..." />
```

**Comment by NVentimiglia** [comment]
This looks like an SDK / product issue and not a issue related to the samples. Please report this issue to SDK Support :

https://groups.google.com/g/google-admob-ads-sdk
