### ISSUE TITLE
Internal Error on different emulators

### ISSUE THREAD

**Issue by ValeryRrR** [googleads/googleads-mobile-android-examples#455]
https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/NativeAdvancedExample
On different emulators, found on galaxy nexus , Nexus S, detected on android 7.1
Ad failed to load - Internal Error the full error can be seen in the screenshot
On other emulators (Pixel 4) and a real device, Native Advanced works well
![IMG_20220725_192351_900](https://user-images.githubusercontent.com/42492624/180827613-bc2a2ca3-7ced-4bbe-97a5-7aa34fdf24aa.png)

**Comment by ericleich** [comment]
Can you try posting this to the [developer forum](https://groups.google.com/g/google-admob-ads-sdk)? My guess is it’s just a no fill in some of those devices but the SDK parses the no fill response as “invalid” for some reason. I don’t think it’s the sample itself causing the issue.

**Comment by ValeryRrR** [comment]
Thanks for answer. I wrote on the link you sent

If someone comes across this problem in the future, maybe solution will be here:
https://groups.google.com/g/google-admob-ads-sdk/c/FAisbz2xdyU

**Comment by ericleich** [comment]
Thanks. Will close the issue here and let discussion continue there.
