### ISSUE TITLE
How to avoid blinking ads upon orientation change?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-examples#47]
In the sample of the banner ad, after if loaded the ad and shows it, I change the orientation, and the ad is gone and re-loads itself.

How can I avoid this, without using configChanges ?

**Comment by ericleich** [comment]
The ad itself is tied to the view, and as you know, when you don't use configChanges, the activity gets destroyed/recreated and all the views get destroyed with it. There is currently no workaround for this outside of config changes.

**Comment by AndroidDeveloperLB** [comment]
The view gets re-created, but why load the ad again from the Internet?
It's a really bad UX to have an ad load itself again and again, for each
new Activity and orientation change.

Why not use caching?
Just cache the ad to the RAM, and re-use it.

Not only that, but you can cache to storage (you can let us choose where to
cache, this would be nice), so that in future runs of the app, loading the
ad would be nearly instant, and you won't even need to access the Internet
every single time.

Anyway, I've written a new post for this, here:
https://github.com/googleads/googleads-mobile-android-examples/issues/48

**Comment by ericleich** [comment]
Answered in other issue.

**Comment by AndroidDeveloperLB** [comment]
@ericleich What other issue?
The one I suggest to use caching ? 
But here it's a question. You didn't answer how to avoid this. I don't consider re-loading of ads a good UX, for each time the user goes between activities...
