### ISSUE TITLE
Native Ad content not displaying

### ISSUE THREAD

**Issue by m-anshuman2166** [googleads/googleads-mobile-android-examples#473]
All works fine, But Native ads mediacontent doesnt displau

Someone kindly take a look at the apk

https://drive.google.com/file/d/1cM2xiYb-obNQJHoaWI1QdvFKg9k6CVBU/view?usp=sharing

**Comment by papaBearClinton** [comment]
> All works fine, But Native ads mediacontent doesnt displau
> 
> Someone kindly take a look at the apk
> 
> https://drive.google.com/file/d/1cM2xiYb-obNQJHoaWI1QdvFKg9k6CVBU/view?usp=sharing

Have you created a native ad view container for the media content?

**Comment by JillSong** [comment]
I can't access the drive link. Feel free to re-open the case if you still encounter the issue with steps to reproduce.
