### ISSUE TITLE
App closing if I've used sdk initialize function 

### ISSUE THREAD

**Issue by jewelshkjony** [googleads/googleads-mobile-android-examples#474]
After using this function, app is crashing

MobileAds.initialize(this, new OnInitializationCompleteListener() {
            @Override
            public void onInitializationComplete(InitializationStatus initializationStatus) {
            }
        });

If I've remove this and compile the app and run, then app is running and can show ad. 
I can't initialize sdk on Samsung phones. 
Please fix this issue.

**Comment by AlexUrrutia** [comment]
You need to add appID tag in the manifest

**Comment by JillSong** [comment]
Feel free to reopen if you still encounter the problem after adding the App ID.
