### ISSUE TITLE
RewardedVideoExample - rewardItem.getAmount()

### ISSUE THREAD

**Issue by SimpGameDev** [googleads/googleads-mobile-android-examples#475]
Where exactly do you set the reward amount?
[RewardedVideoExample](https://github.com/googleads/googleads-mobile-android-examples/blob/main/java/admob/RewardedVideoExample/app/src/main/java/com/google/ads/rewardedvideoexample/MainActivity.java)  

`new OnUserEarnedRewardListener() {  
          @Override  
          public void onUserEarnedReward(@NonNull RewardItem rewardItem) {   
            // Handle the reward.
            Log.d("TAG", "The user earned the reward.");
            int rewardAmount = rewardItem.getAmount();
            String rewardType = rewardItem.getType();
          }
        });`

**Comment by JillSong** [comment]
In the AdMob UI https://support.google.com/admob/answer/7311747?hl=en-GB&ref_topic=7384409&sjid=13141608972753541384-EU.
