### ISSUE TITLE
Atomic Reference when display interstitial

### ISSUE THREAD

**Issue by AdilSattar1233** [googleads/googleads-mobile-android-examples#479]
D/LeakCanary: 1 APPLICATION LEAKS
D/LeakCanary: 
D/LeakCanary: References underlined with "~~~" are likely causes.
D/LeakCanary: Learn more at https://squ.re/leaks.
D/LeakCanary: 
D/LeakCanary: 8365695 bytes retained by leaking objects
D/LeakCanary: Signature: 0774a0a63f6f4221ebbd1ef033208dfc0653f01b
D/LeakCanary: ┬───
D/LeakCanary: │ GC Root: Global variable in native code
D/LeakCanary: │
D/LeakCanary: ├─ com.google.android.gms.dynamic.ObjectWrapper instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 528 B in 1 objects
D/LeakCanary: │    ↓ ObjectWrapper.a
D/LeakCanary: │                    ~
D/LeakCanary: ├─ com.google.android.gms.ads.nonagon.ad.event.n instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 473 B in 14 objects
D/LeakCanary: │    ↓ dv.b
D/LeakCanary: │         ~
D/LeakCanary: ├─ java.util.HashMap instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 388 B in 12 objects
D/LeakCanary: │    ↓ HashMap[key()]
D/LeakCanary: │             ~~~~~~~
D/LeakCanary: ├─ com.google.android.gms.ads.nonagon.ad.event.dv instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 236 B in 8 objects
D/LeakCanary: │    ↓ dv.b
D/LeakCanary: │         ~
D/LeakCanary: ├─ java.util.HashMap instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 224 B in 7 objects
D/LeakCanary: │    ↓ HashMap[key()]
D/LeakCanary: │             ~~~~~~~
D/LeakCanary: ├─ com.google.android.gms.ads.nonagon.shim.y instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 8.4 MB in 2442 objects
D/LeakCanary: │    ↓ y.a
D/LeakCanary: │        ~
D/LeakCanary: ├─ java.util.concurrent.atomic.AtomicReference instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 29.9 kB in 1041 objects
D/LeakCanary: │    ↓ AtomicReference.value
D/LeakCanary: │                      ~~~~~
D/LeakCanary: ├─ com.google.android.gms.ads.internal.client.aq instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 29.9 kB in 1040 objects
D/LeakCanary: │    ↓ aep.a
D/LeakCanary: │          ~
D/LeakCanary: ├─ com.google.android.gms.ads.internal.client.zzh instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 29.8 kB in 1038 objects
D/LeakCanary: │    ↓ zzh.zza
D/LeakCanary: │          ~~~
D/LeakCanary: ├─ com.fofapps.pro.app.locker.FofAppsSplashActivity$3 instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 12 B in 1 objects
D/LeakCanary: │    Anonymous subclass of com.google.android.gms.ads.interstitial.InterstitialAdLoadCallback
D/LeakCanary: │    this$0 instance of com.fofapps.pro.app.locker.FofAppsSplashActivity with mDestroyed = true
D/LeakCanary: │    ↓ FofAppsSplashActivity$3.this$0
D/LeakCanary: │                              ~~~~~~
D/LeakCanary: ╰→ com.fofapps.pro.app.locker.FofAppsSplashActivity instance
D/LeakCanary: ​     Leaking: YES (ObjectWatcher was watching this because com.fofapps.pro.app.locker.FofAppsSplashActivity received
D/LeakCanary: ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
D/LeakCanary: ​     Retaining 8.4 MB in 1377 objects
D/LeakCanary: ​     key = f979ed4d-011f-42ed-97c4-caea47800819
D/LeakCanary: ​     watchDurationMillis = 13656
D/LeakCanary: ​     retainedDurationMillis = 8653
D/LeakCanary: ​     mActivity instance of com.fofapps.pro.app.locker.FofAppsSplashActivity with mDestroyed = true
D/LeakCanary: ​     mApplication instance of com.fofapps.pro.app.locker.fof_apps_app.FofApps2MyApplication
D/LeakCanary: ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper

**Comment by JillSong** [comment]
I can't reproduce with the current sample. Feel free to re-open if you still encounter the issue, with steps to reproduce.
