### ISSUE TITLE
Support localhost on WebView API for Ads

### ISSUE THREAD

**Issue by ollm** [googleads/googleads-mobile-android-examples#481]
Currently [WebView API for Ads](https://developers.google.com/admob/android/webview) not work if the WebView is in `localhost`, some web applications like those made with cordova/ionic uses `localhost` for the WebView and it is not possible to show ads in these apps.

**Comment by JillSong** [comment]
Thank you for raising this. Feature request submitted.

**Comment by ollm** [comment]
Thank you for considering the feature request.

There is something else about the cordova/ionic WebView that I didn't know at the time, on iOS they have to use a different scheme than `http/https`, they use `app://` normally for cordova and `ionic://` for ionic.

I don't know if this should also be considered in the feature request (This only affects iOS since `https` can be used on Android)

More info: https://github.com/apache/cordova-ios/issues/1227#issuecomment-1077926233

Examples: 

- Cordova: `app://localhost`  or `app://example.com`
- Ionic: `ionic://localhost` or `ionic://example.com`
