### ISSUE TITLE
Story ads

### ISSUE THREAD

**Issue by BrianTum** [googleads/googleads-mobile-android-examples#486]
Hello team, there is a new trend in the market. Story content, as documented in one of googles projects [amp stories](https://amp.dev/about/stories/). It's gotten pace in mobile and mobile users enjoy this content. however, google has not provided a monetization for this type of content. 

I would like to help the team, wherever possible to leverage this opportunity for the advantage of google, developers, publishers and mobile users.

**Comment by JillSong** [comment]
Thank you for reaching out and sharing with us @BrianTum ! We acknowledge your contribution.
