### ISSUE TITLE
banner recycler issue

### ISSUE THREAD

**Issue by smoil-ali** [googleads/googleads-mobile-android-examples#496]
I saw your implementation, I think this implementation has one loophole. when one ad is loaded then the onLoaded event gets called and you load the next ad, it is quite interesting. but the problem is when the ad refresh again onLoaded event is called and it loads the next ad which we don't need. On average ad views, and refresh is set to 30 to 50 seconds. It means after every 30 seconds ad will load that we don't need.
It will increase the requests and our show rate will be down. I hope you understand my question and will make a solution to it.

**Comment by JillSong** [comment]
It's up to you to find the balance between latency and show rate. It's a common practice to pre-load multiple ads to place in a recycler review even if they don't end up getting shown. 

Our example request ads sequentially, but we plan to modify it to load multiple ads at front.
