### ISSUE TITLE
Sample code cannot be build in eclipse

### ISSUE THREAD

**Issue by ericwongcm** [googleads/googleads-mobile-android-examples#5]
After I imported the admob sample codes to eclipse and then added library to the sample code, I can't build the sample app.

Eclipse will report an error saying it run out of heap space or similar.
And eclipse will ask you to exit workbench or not.
-----------
I am able to use the admob XML method to integrate banner ads.
Note: building the xml sample code directly will cause problem in eclipse too.. 
The banner shows up fine but log keep saying...

"The Google Play services resources were not found. Check your project configuration to ensure that the resources are included."

I tried the java method too but it didn't work.
So, I currently settle on the XML method but I have no idea if this problem is going to cause any problems if I release the app publicly.

I have already added admob library to my app as instructed at
https://developers.google.com/mobile-ads-sdk/docs/

I see some people suggest ticking the Google API instead of Android API but that does not seems to make any difference.

I also tried to use the froyo admob library too but eclipse won't build.
Eclipse keep complaining the library (com.google.android.gms.ads) not found or similar.

Any idea how to solve this? or what is going on?
Since I can't build the sample code, I can't be sure if the sample code provided actually works.

**Comment by rampara** [comment]
Closing issue due to its age. If this issue still persists for you, please re-open it.
