### ISSUE TITLE
documentation is outdated?

### ISSUE THREAD

**Issue by iulianflst** [googleads/googleads-mobile-android-examples#502]
The example does not work, It looks like is outdated

![image](https://user-images.githubusercontent.com/1937701/205520642-9644c23b-263d-466f-8773-4c01d09b7f2b.png)

I followed the instructions from here
https://developers.google.com/admob/android/app-open?hl=en-GB

So if official documentation is outdated, then where can I find a hello world example at least....?

**Comment by JillSong** [comment]
The issue seems fixed. Thanks for reporting.
