### ISSUE TITLE
Unable to do delayed initialization of Google advertising SDK

### ISSUE THREAD

**Issue by yanxiong-github** [googleads/googleads-mobile-android-examples#503]
The access of Google ads resulted in high startup time and anr of our application, Details are as follows:
![ads](https://user-images.githubusercontent.com/49550347/205589882-ccb56108-e4f6-453e-9b86-122e04398f9d.png)

Currently the initialization is done through the Provider in the manifest file, we want to remove it and delay the manual initialization，The status quo is as follows：
![gms](https://user-images.githubusercontent.com/49550347/205590914-0b5ee6cb-ec2e-42b2-b84d-443f15965f22.png)

We want to solve this problem by delaying the initialization of Google ads，However, no corresponding method for delayed initialization is found in the official documentation，Could you please tell me what I should do？

**Comment by JillSong** [comment]
Hi @yanxiong-github , you can try this feature https://developers.devsite.corp.google.com/admob/android/optimize-initialization and let us know if you have further questions.
