### ISSUE TITLE
Memory leak caused by MobileAds.registerWebView

### ISSUE THREAD

**Issue by Just4fun2021** [googleads/googleads-mobile-android-examples#510]
I add MobileAds.registerWebView (webView) in activity onCreate; However, a memory leak was found, When I delete this code, I will not prompt for memory leak How to solve this problem?

GC Root: Thread object
│
├─ Dk instance
│    Leaking: NO (PathClassLoader↓ is not leaking)
│    Thread name: 'CleanupReference'
│    ↓ Thread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (zzbzz↓ is not leaking and A ClassLoader is never leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (zzbzz↓ is not leaking)
│    ↓ Object[2266]
├─ com.google.android.gms.internal.ads.zzbzz class
│    Leaking: NO (a class is never leaking)
│    ↓ static zzbzz.zza
│                   ~~~
├─ com.google.android.gms.internal.ads.zzcfk instance
│    Leaking: UNKNOWN
│    Retaining 16 B in 1 objects
│    ↓ zzasd.zza
│            ~~~
├─ com.google.android.gms.ads.nonagon.signalgeneration.ab instance
│    Leaking: UNKNOWN
│    Retaining 379.4 kB in 5156 objects
│    e instance of sg.just4fun.tgasdk.ui.HomeActivity with mDestroyed = true
│    ↓ ab.e
│         ~
╰→ xxx.xxx.WebViewActivity instance
​     Leaking: YES (ObjectWatcher was watching this because xxx.xxx.WebViewActivity received Activity#onDestroy() callback and
​     Activity#mDestroyed is true)
​     Retaining 376.6 kB in 5078 objects
​     key = 9500b00e-35f4-476d-bb2e-836c21f4c80f
​     watchDurationMillis = 7971
​     retainedDurationMillis = 2971
​     mApplication instance of com.just4fun.tga.App
​     mBase instance of androidx.appcompat.view.ContextThemeWrapper

**Comment by JillSong** [comment]
If you are still experiencing this issue can you please open a case on the [google mobile ads support forum](https://groups.google.com/g/google-admob-ads-sdk)? Please include a network trace and device trace of the incident so we can look into this for you.
