### ISSUE TITLE
Failed to Load native ad: 0

### ISSUE THREAD

**Issue by android-xiaowei** [googleads/googleads-mobile-android-examples#52]
I'm using the "NativeAdvancedExample" demo to run, 'https://github.com/googleads/googleads-mobile-android-examples/tree/master/admob/NativeAdvancedExample' .

This demo load "content ads" success, but load "app install ads" faild, error message "Failed to Load native ad: 0"

I didn't change the code.

**Comment by ericleich** [comment]
Hi there,

Does your device have multiple apps on the phone that can respond to market:// urls? If there is another app other than the play store that handles those URLs, it currently results in app install ads not being returned. This actually happened on one of my test devices and removing the other app addressed the issue.

**Comment by ericleich** [comment]
Closing this out due to lack of response and because I'm fairly confident that's the issue. We are also working how to make the SDK support the multi-store use case so it'll work for all users down the line.
