### ISSUE TITLE
I was not watch the full video, but I get reward.

### ISSUE THREAD

**Issue by 15915763299** [googleads/googleads-mobile-android-examples#536]
When I closed the ad video with the top button, and now the ad video was not finish, but the function “onUserEarnedReward” was invoked. It's correct? I was not watch the full video, but I get reward.

**Comment by JillSong** [comment]
Yes, reward can be granted without the full video being played.

"The user is shown a close button with a countdown timer that shows the number of seconds remaining before the user receives the reward."
https://support.google.com/admob/answer/7372450?hl=en-GB
