### ISSUE TITLE
[GoogleAds] Unable to load the SDK on-demand

### ISSUE THREAD

**Issue by uKetki** [googleads/googleads-mobile-android-examples#537]
Hi Team, 

I made modifications to the [android-dynamic-features](https://github.com/googlecodelabs/android-dynamic-features) sample app by including the GoogleAdsSDK as a dynamic feature module in the [Java](https://github.com/googlecodelabs/android-dynamic-features/tree/master/features/java) module. Despite explicitly adding the google_play_services_version value to the AndroidManifest file, the test app is crashing at the `com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable` step, and I am seeing the following error logs:

```
* What went wrong:
Execution failed for task ':app:bundleReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable
   > Android resource linking failed
     ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:131: AAPT: error: resource integer/google_play_services_version (aka com.google.android.samples.dynamicfeatures.ondemand:integer/google_play_services_version) not found.

     ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:163: AAPT: error: resource bool/enable_system_alarm_service_default (aka com.google.android.samples.dynamicfeatures.ondemand:bool/enable_system_alarm_service_default) not found.

     ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:169: AAPT: error: resource bool/enable_system_job_service_default (aka com.google.android.samples.dynamicfeatures.ondemand:bool/enable_system_job_service_default) not found.

     ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:176: AAPT: error: resource bool/enable_system_foreground_service_default (aka com.google.android.samples.dynamicfeatures.ondemand:bool/enable_system_foreground_service_default) not found.

     ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:238: AAPT: error: resource bool/enable_system_alarm_service_default (aka com.google.android.samples.dynamicfeatures.ondemand:bool/enable_system_alarm_service_default) not found.
```

Below is the list of changes to make the SDK available on-demand:
```
diff --git a/build.gradle b/build.gradle
index ecf3355..164b853 100644
--- a/build.gradle
+++ b/build.gradle
@@ -20,7 +20,7 @@ buildscript {
 
     ext.versions = [
             'compileSdk'        : 31,
-            'minSdk'            : 16,
+            'minSdk'            : 19,
             'targetSdk'         : 31,
             'kotlin'            : '1.6.10',
             'playcore'          : '1.10.3',
diff --git a/features/java/build.gradle b/features/java/build.gradle
index 1d7e704..da7dcca 100644
--- a/features/java/build.gradle
+++ b/features/java/build.gradle
@@ -27,4 +27,5 @@ android {
 
 dependencies {
     implementation project(':app')
+    implementation 'com.google.android.gms:play-services-ads:21.1.0'
 }
diff --git a/features/java/src/main/AndroidManifest.xml b/features/java/src/main/AndroidManifest.xml
index 2bcd40c..5e15d35 100644
--- a/features/java/src/main/AndroidManifest.xml
+++ b/features/java/src/main/AndroidManifest.xml
@@ -33,6 +33,14 @@
                 <action android:name="android.intent.action.VIEW" />
             </intent-filter>
         </activity>
+
+        <meta-data
+            android:name="com.google.android.gms.version"
+            android:value="@integer/google_play_services_version" />
+
+        <meta-data
+            android:name="com.google.android.gms.ads.APPLICATION_ID"
+            android:value="abcd"/>
     </application>
 
 </manifest>
```

Additionally, we would like to determine the amount of binary space we can save by using the SDK on-demand.

Thanks!

**Comment by hau99** [comment]
> Hi Team, 
> 
> I made modifications to the [android-dynamic-features](https://github.com/googlecodelabs/android-dynamic-features) sample app by including the GoogleAdsSDK as a dynamic feature module in the [Java](https://github.com/googlecodelabs/android-dynamic-features/tree/master/features/java) module. Despite explicitly adding the google_play_services_version value to the AndroidManifest file, the test app is crashing at the `com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable` step, and I am seeing the following error logs:
> 
> ```
> * What went wrong:
> Execution failed for task ':app:bundleReleaseResources'.
> > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable
>    > Android resource linking failed
>      ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:131: AAPT: error: resource integer/google_play_services_version (aka com.google.android.samples.dynamicfeatures.ondemand:integer/google_play_services_version) not found.
> 
>      ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:163: AAPT: error: resource bool/enable_system_alarm_service_default (aka com.google.android.samples.dynamicfeatures.ondemand:bool/enable_system_alarm_service_default) not found.
> 
>      ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:169: AAPT: error: resource bool/enable_system_job_service_default (aka com.google.android.samples.dynamicfeatures.ondemand:bool/enable_system_job_service_default) not found.
> 
>      ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:176: AAPT: error: resource bool/enable_system_foreground_service_default (aka com.google.android.samples.dynamicfeatures.ondemand:bool/enable_system_foreground_service_default) not found.
> 
>      ERROR:/Users/ketki/GoogleAppBundlesSample/android-dynamic-features/app/build/intermediates/bundle_manifest/release/AndroidManifest.xml:238: AAPT: error: resource bool/enable_system_alarm_service_default (aka com.google.android.samples.dynamicfeatures.ondemand:bool/enable_system_alarm_service_default) not found.
> ```
> 
> Below is the list of changes to make the SDK available on-demand:
> ```
> diff --git a/build.gradle b/build.gradle
> index ecf3355..164b853 100644
> --- a/build.gradle
> +++ b/build.gradle
> @@ -20,7 +20,7 @@ buildscript {
>  
>      ext.versions = [
>              'compileSdk'        : 31,
> -            'minSdk'            : 16,
> +            'minSdk'            : 19,
>              'targetSdk'         : 31,
>              'kotlin'            : '1.6.10',
>              'playcore'          : '1.10.3',
> diff --git a/features/java/build.gradle b/features/java/build.gradle
> index 1d7e704..da7dcca 100644
> --- a/features/java/build.gradle
> +++ b/features/java/build.gradle
> @@ -27,4 +27,5 @@ android {
>  
>  dependencies {
>      implementation project(':app')
> +    implementation 'com.google.android.gms:play-services-ads:21.1.0'
>  }
> diff --git a/features/java/src/main/AndroidManifest.xml b/features/java/src/main/AndroidManifest.xml
> index 2bcd40c..5e15d35 100644
> --- a/features/java/src/main/AndroidManifest.xml
> +++ b/features/java/src/main/AndroidManifest.xml
> @@ -33,6 +33,14 @@
>                  <action android:name="android.intent.action.VIEW" />
>              </intent-filter>
>          </activity>
> +
> +        <meta-data
> +            android:name="com.google.android.gms.version"
> +            android:value="@integer/google_play_services_version" />
> +
> +        <meta-data
> +            android:name="com.google.android.gms.ads.APPLICATION_ID"
> +            android:value="abcd"/>
>      </application>
>  
>  </manifest>
> ```
> 
> Additionally, we would like to determine the amount of binary space we can save by using the SDK on-demand.
> 
> Thanks!

**Comment by JillSong** [comment]
Hi @uKetki , the problem doesn't seem to be related to this repo.

The correct package name of the Google Mobile Ads SDK is com.google.android.gms:play-services-ads.

**Comment by cleverpo** [comment]
Hi @uKetki , I have same problem in this issue. Has any solutions you got?

**Comment by henriquehsv** [comment]
@cleverpo We have found the issue, it's related to DFMs.
It's fixed on Android 15, but there are a few workarounds you can use to avoid it, including using ReLinker to load your library:
https://issuetracker.google.com/issues/346717090
