### ISSUE TITLE
How can we show Native ad programmatically?

### ISSUE THREAD

**Issue by jewelshkjony** [googleads/googleads-mobile-android-examples#539]
I want to show native ad without using any xml view. Actually I'm using “Mit App Inventor 2” online platform to build application. There I can only use Java to integrate Admob sdk.
I can show banner ad without xml by programmatically. But I can't show native ad properly by programmatically.
So please help me to implement native ad programmatically without using any xml layout.
(Thanks)

**Comment by ericleich** [comment]
Creating a layout programmatically is not much different than creating any other layout programmatically. I couldn't find an official Android tutorial on this, but there are many 3rd party ones if you just google search something like "android add views programmatically".

Things to consider for the native ads layout specifically:

1. The top-level view should be of type [NativeAdView](https://developers.google.com/android/reference/com/google/android/gms/ads/nativead/NativeAdView).
2. All asset views should be children of this NativeAdView in the view hierarchy.
3. Each of the asset views you create need to be registered on the NativeAdVIew (in addition to just adding the views into the view hierarchy). This is effectively the same code as [here](https://github.com/googleads/googleads-mobile-android-examples/blob/5e38527c3b09b63a0bdb7a0ef90a165f9df5e36e/java/admob/NativeAdvancedExample/app/src/main/java/com/google/example/gms/nativeadvancedexample/MainActivity.java#L95-L194) that you'd need to add regardless of whether your native ad is defined in XML or through code.

Here's some sample code to get you started, but I recommend following a 3rd party tutorial for more information on creating views programmatically:

```
// Recreate view from https://github.com/googleads/googleads-mobile-android-examples/blob/main/java/admob/NativeAdvancedExample/app/src/main/res/layout/ad_unified.xml in code.
NativeAdView view = new NativeAdView(this);
LinearLayout layout = new LinearLayout(this);
view.addView(layout);
// This deviates from the layout above, just shown as an example.
TextView headlineView = new TextView(this);
// Assumes you have a loaded nativeAd object when creating these views, to set data.
headlineView.setText(nativeAd.getHeadline());
LinearLayout.LayoutParams headlineParams = new LinearLayout.LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
layout.addView(headlineView, headlineParams);
// Don't forget to register assets with the nativeAdView.
// This tells the SDK which asset this view represents, and enables that view for click tracking.
// More details about setting view data and registering assets are available at:
// https://github.com/googleads/googleads-mobile-android-examples/blob/5e38527c3b09b63a0bdb7a0ef90a165f9df5e36e/java/admob/NativeAdvancedExample/app/src/main/java/com/google/example/gms/nativeadvancedexample/MainActivity.java#L95-L194
view.setHeadlineView(headlineView).
```
