### ISSUE TITLE
AdView is Blank!

### ISSUE THREAD

**Issue by JeniferJethrouth** [googleads/googleads-mobile-android-examples#55]
Admob is not visible. It  worked fine before a month but now its not at all visible in many devices. Even test ad also not working. Rarely admob comes, most of the time the view is blank only.

**Comment by ericleich** [comment]
Which format are you using?

Test ads weren't working 2 days ago but should have been fixed before your comment 10 hours ago.

**Comment by JeniferJethrouth** [comment]
Sometime adview is visible sometime is empty. Its not working,even i changed  Ad unit id .

**Comment by ericleich** [comment]
I need more information to help you debug. Are you running one of the samples from this repo and still not getting ads back? Which one?

**Comment by JeniferJethrouth** [comment]
Yes i checked BannerExample project. am not getting ads. its saying error code 2. i also switched from wifi to mobile data ,Ad is coming one time after some time its not at all coming. i also checked with many devices

**Comment by ericleich** [comment]
I'm getting back the banner ad when downloading and running the AdMob Banner example out of the box, so it's not a network-wide problem.

Error code 2 is a [network error](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest.html#ERROR_CODE_NETWORK_ERROR).  Can you confirm:

1. You can use Chrome to successfully access the internet
2. Your device doesn't have an ad blocker installed

**Comment by ericleich** [comment]
Closing this issue as duplicate of #60
