### ISSUE TITLE
app open ads for children

### ISSUE THREAD

**Issue by nboy1** [googleads/googleads-mobile-android-examples#550]
i don't know where i read before that it's not permissible to use app open ads if your application designed for kids, but now i tried to be sure of this i searched in every possible way in internet, but i couldn't find anything that talk about this.
is app open ads permissible to use it in application that designed for kids?  
sorry if this is not the right place to ask this question.

**Comment by ericleich** [comment]
https://support.google.com/admob/answer/9341964 has a note stating this explicitly:

```
Note: Apps that are in Google Play’s Designed for Families program are not eligible to use app open ads.
```
