### ISSUE TITLE
Clarification on enforcing app-level frequency capping for AdMob ads

### ISSUE THREAD

**Issue by shwuhk** [googleads/googleads-mobile-android-examples#556]
## Issue Title
Clarification on enforcing app-level frequency capping for AdMob ads

## Issue Description
I'm currently integrating AdMob ads into my app and I would like to enforce an app-level frequency cap to limit the number of times ads are shown to a user across all ad formats within a specific time period. However, I have a question regarding the implementation details.

## Question
I have both interstitial ads and reward ads in my app, and I want to set a frequency cap that applies to both ad formats collectively at the app level. In other words, I want to ensure that the total number of ad impressions, regardless of the ad format, does not exceed a certain limit within a given time frame.

Is there a recommended approach or best practice to enforce an app-level frequency cap in AdMob? How can I achieve this without having to clear all ads each time to ensure the frequency cap is respected?

Any insights or guidance on implementing an app-level frequency cap for multiple ad formats in AdMob would be greatly appreciated.

## Additional Information
- AdMob SDK version: 21.5.0
- Platform: Android

Thank you in advance for your assistance!

**Comment by NVentimiglia** [comment]
Hi @shwuhk,

Thanks for reaching out.

I understand that you're trying to implement frequency capping for AdMob, but you're having trouble.

GitHub is best for code-specific issues relating to the sample. If you're having trouble with a product-related issue, such as frequency capping, I recommend that you visit the AdMob Community Forum or Help Center.

* [AdMob Community Forum](https://support.google.com/admob/thread/new?hl=en&help_center_link=[6244508,%22Set%20frequency%20capping%20for%20apps%20\u0026amp;%20ad%20units%22]&sjid=13917111237387203821-NA)
* [AdMob Help Center](https://support.google.com/admob/answer/6244508?hl=en&sjid=13917111237387203821-NA)

I hope this helps!
