### ISSUE TITLE
Admob Stopped serving ads

### ISSUE THREAD

**Issue by mukeshsolanki** [googleads/googleads-mobile-android-examples#57]
We have 2 apps in production on the play store. Admob has suddenly stopped serving ads. It seems to be returning `Failed to load ads: 0` These apps are on production and need high priority. It occasionally loads the ads.

**Comment by ericleich** [comment]
Is this still the rewarded ads similar to Issue #54?

Please provide a link to your app on Google play so we can try reproducing on our end.

**Comment by ericleich** [comment]
Also, next time, please ask this question on the [AdMob develeloper forum](https://groups.google.com/group/google-admob-ads-sdk) instead. This question is outside the context of the sample apps.
