### ISSUE TITLE
NativeExpressRecyclerViewExample does not show ads on Samsung Note 3 (Android 5.0, API 21)

### ISSUE THREAD

**Issue by janicetan12** [googleads/googleads-mobile-android-examples#59]
Hi,

Have downloaded the example and run on 3 devices. 
1. Nexus 7
2. Samsung Galaxy S6
3. Samsung Note 3

Have used both the Test ID and our own ID. For devices 1 and 2, the ads load ok. But it doesn't load on device 3. Is there some issues with older SDK?

Thanks.

**Comment by ericleich** [comment]
Hi there,

I don't have a Note 3 on hand, but I tried on an API 21 emulator and am getting ads back with the test ad unit. What error code are you getting when the ad fails to load? Any logcat output you can share?

Thanks,
Eric

**Comment by janicetan12** [comment]
Hi,

I managed to get ads on all 3 devices and on both Ad Ids the following day. And i just checked it again today, the ads are loading fine. So i'm just as puzzled how they suddenly worked after 1 day. 

Here's the log i had saved if it helps in the future.

```
Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
Starting ad request.
There was a problem getting an ad response. ErrorCode: 0
Failed to load ad: 0
The previous Native Express ad failed to load. Attempting to load the next Native Express ad in the items list.
```

**Comment by ericleich** [comment]
Newly created ad units take about an hour to start serving. And yes, during that time you get error code 0 (Internal error) instead of error code 3 (no fill). Since it all started working magically after some time, I'm pretty sure that was your issue.
