### ISSUE TITLE
 Inquiry Regarding Access to Banner Ad Types (Rich Media vs. Video) from AdMob

### ISSUE THREAD

**Issue by stuhua** [googleads/googleads-mobile-android-examples#590]
I am a developer currently integrating the AdMob ad library into my application. I am working on displaying Banner ads within my app and would like to have the ability to determine the specific type of each ad, such as whether it is a Rich Media ad or a Video ad. After reviewing the documentation, I did not find a direct method to retrieve the Banner ad type, so I am reaching out to inquire if there is a way to access this information.

I have gone through the official AdMob documentation, but I was unable to find any specific instructions related to the information I am seeking. I am interested in understanding if there is a mechanism, such as an attribute within the ad callback, or any other method, that could assist me in identifying the type of Banner ad being delivered. This information would greatly assist me in refining the ad presentation and enhancing the overall user experience.

**Comment by NVentimiglia** [comment]
Hi @stuhua 

The closest we have is testing specific creative types https://developers.google.com/admob/android/test-creative-types

If you would like, you can open up a feature request [here](https://groups.google.com/g/google-admob-ads-sdk). Please include specifics on your use case and why this data is needed. For instance describing how you may change your app based on an html vs video ad would help push this initiative forward.
