### ISSUE TITLE
Native ads not working well on the Jetpack Compose

### ISSUE THREAD

**Issue by Nghicv** [googleads/googleads-mobile-android-examples#591]
Issue: https://groups.google.com/g/google-admob-ads-sdk/c/mIcpNEhKY7M
Please add a demo to use ads in the Jetpack Compose

**Comment by NVentimiglia** [comment]
Closing this as a duplicate [https://github.com/googleads/googleads-mobile-android-examples/issues/450]. 

This is an enhancement under consideration.
