### ISSUE TITLE
Interstitial Ad Taking Too Much Time To Load and Show 

### ISSUE THREAD

**Issue by tauseeq-grace** [googleads/googleads-mobile-android-examples#599]
i Have Done Implementation of Interstitial Ad according To Google AdmobSDK, But Interstitial Ad Taking 11 to 12 Second and Sometime 7 or 8 Second to load the ad why? The Code was Working Fine before it was taking approximately 2-3 Seconds to load the ads and than show. But suddenly this issue is occuring what is the reason ? anyone can help or guide ?

**Comment by NVentimiglia** [comment]
Hi @tauseeq-grace 

Loading an ad is a network request and may take some time. We recommend preloading the ad before you need it.

If this does not help, please share your implementation code and we can take a look.

**Comment by tauseeq-grace** [comment]
But at Splash i have tried Sending Request of Ad Load in Application Class but Ad Load Response Came after 7 to 8 Seconds and in that time i have navigated to Next Screen than ad is Loaded  got my Point 
`      fun loadInterstitialAd(
        context: Context,
        adInterId: String,
        listener: (Boolean) -> Unit
    ) {
        if (!isAdLoaded && admobInterAd == null) {
            isAdLoaded = true
            val adRequest = AdRequest.Builder().build()
            InterstitialAd.load(context, adInterId, adRequest,
                object : InterstitialAdLoadCallback() {
                    override fun onAdFailedToLoad(ad: LoadAdError) {
                        Log.e(Constants.TAG, "onAdFailedToLoad - $ad")
                        admobInterAd = null
                        isAdLoaded = false
                        listener.invoke(false)
                    }

                    override fun onAdLoaded(ad: InterstitialAd) {
                        admobInterAd = ad
                        isAdLoaded = true
                        listener.invoke(true)
                    }
                })
        }
    }
   `
   when this Callback trigger i actually show the ad and move to Next Screen after Ad Dismissed

**Comment by NVentimiglia** [comment]
@tauseeq-grace 

`InterstitialAd.load()` is a network call and may be affected by network conditions such as poor wifi. To diagnose this we will need to look at a [network trace](https://developers.google.com/admob/android/charles) of the request. Please open a case on the official [Google support group](https://groups.google.com/g/google-admob-ads-sdk) as they have the tools to best help you.

**Comment by tauseeq-grace** [comment]
I have Checked the Network Traces  also the internet connection is in good conditions. I Have First Checked the all these scenarios than i post comment. 
Thanks for your help i have posted my query in official [Google support group](https://groups.google.com/g/google-admob-ads-sdk) also .. 
i am using the sdk version 
    api 'com.google.android.gms:play-services-ads-lite:22.3.0'

**Comment by tauseeq-grace** [comment]
@NVentimiglia No Reply From Google Support Group:
Log.e(Constants.TAG, "Interstitial Ad Loading Request....")
val adRequest = AdRequest.Builder().build()
Handler(Looper.getMainLooper()).postDelayed({
InterstitialAd.load(activity,"ca-app-pub-3940256099942544/1033173712", adRequest, object : InterstitialAdLoadCallback() {
override fun onAdFailedToLoad(adError: LoadAdError) {
Log.e(Constants.TAG, "Interstitial AdFailedToLoad - $adError")
mInterstitialAd = null
}

override fun onAdLoaded(interstitialAd: InterstitialAd) {
Log.e(Constants.TAG, "Interstitial Ad Loaded....")
mInterstitialAd = interstitialAd
mInterstitialAd?.show(activity)
mInterstitialAd?.fullScreenContentCallback =
object : FullScreenContentCallback() {
override fun onAdDismissedFullScreenContent() {
Log.e(Constants.TAG, "Interstitial Ad Dismissed ")
Constants.isInterShowing = false
mInterstitialAd = null
isAdLoaded = false
listener.invoke(true)
}

override fun onAdFailedToShowFullScreenContent(p0: AdError) {
super.onAdFailedToShowFullScreenContent(p0)
Log.e(Constants.TAG, "Interstitial AdFailedToShowFullScreenContent - ${p0}")
Constants.isInterShowing = false
isAdLoaded = false
listener.invoke(false)
}

override fun onAdImpression() {
}

override fun onAdShowedFullScreenContent() {
Constants.isInterShowing = true
}
}
}
})
},6000)


Log:
2023-10-03 01:23:37.070 17251-17251 AdsTag                  com.gracetech.adsintegration         E  Interstitial Ad Loading Request....
2023-10-03 01:23:52.288 17251-17251 AdsTag                  com.gracetech.adsintegration         E  Interstitial Ad Loaded....

**Comment by JillSong** [comment]
Closing the issue as this is not directly related to this repo. Please post on https://developers.google.com/admob/android/support for any SDK related question. Thanks!
