### ISSUE TITLE
Crash Application and unable pause activity in interstitial 

### ISSUE THREAD

**Issue by Gupta126** [googleads/googleads-mobile-android-examples#6]
i want to show ads in my app 
where i am using fragments  and i want to handle onAdclosed method 
in that method i want to replace fragment but it fails to replace and and error causes 
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to pause activity  
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1280)

please provide some solution

**Comment by rampara** [comment]
The [Advanced API Demo](https://github.com/googleads/googleads-mobile-android-examples/tree/master/advanced/APIDemo) should serve as an example of how to correctly integrate ads and handle ad events in an app that uses fragments.
