### ISSUE TITLE
The setHttpTimeoutMillis method is invalid

### ISSUE THREAD

**Issue by fringesy** [googleads/googleads-mobile-android-examples#601]
Here's my code：

`AdRequest.Builder().setHttpTimeoutMillis(8 * 1000).build()`

But I still waited at least 10 seconds and returned the AD normally. Shouldn't I get a timeout or fail callback at 8 seconds? What went wrong?

My dependency version ：
`'com.google.android.gms:play-services-ads:22.4.0'`

**Comment by NVentimiglia** [comment]
Hi @fringesy,

Can you open up a case on the google support forum? They will be able to help you with this.

https://groups.google.com/g/google-admob-ads-sdk
