### ISSUE TITLE
hasVideoContent() always returns false using UnifiedNativeAdMapper

### ISSUE THREAD

**Issue by Neexol** [googleads/googleads-mobile-android-examples#603]
Hello,
If I use `UnifiedNativeAdMapper` when loading native ads and set the presence of video using `setHasVideoContent()` it has no effect.

**Actual behavior:**
You can reproduce this bug in your example: 
1) In the `SampleUnifiedNativeAdMapper.java` file, add `setHasVideoContent(true)` in the constructor;
2) In the `MainActivity.java` file, in the `onNativeAdLoaded()` callback, `nativeAd.getMediaContent().hasVideoContent()` and `nativeAd.getMediaContent().getVideoController().hasVideoContent()` will return `false`, although they should return `true`.

**Expected behavior:**
`hasVideoContent()` returns `true`

**Comment by NVentimiglia** [comment]
Hi @Neexol 

It sounds like you are writing some sort of mediation adapter? Can you give me a little more context of what you are trying to do, and a complete code sample?

**Comment by Neexol** [comment]
I apologize @NVentimiglia, I got the wrong repository to create the issue, I meant to create it here https://github.com/googleads/googleads-mobile-android-mediation. Here is the [source code](https://drive.google.com/file/d/1sia6eJC81yHZNVHI5jUcUU_9MlNXr5Vx/view?usp=sharing) with my edits that reproduces the bug based on the above repository (too big for direct load).

I have set the use of custom event. Also call `setHasVideoContent(true)` at `L70` in `SampleUnifiedNativeAdMapper.java` and check it at `L235` in `MainActivity.java`.

<img width="683" alt="image" src="https://github.com/googleads/googleads-mobile-android-examples/assets/36748663/a801e6de-f8ff-4731-b60a-8a0802e7a37b">
<img width="872" alt="image" src="https://github.com/googleads/googleads-mobile-android-examples/assets/36748663/0d90f93e-1000-44ad-866e-13fdf12500f1">

**Comment by malandr2** [comment]
@Neexol, please open a new issue in [that repository](https://github.com/googleads/googleads-mobile-android-mediation) with the information you have provided. Closing this is issue as it is not applicable to this repository.
