### ISSUE TITLE
can't load thrid party reward

### ISSUE THREAD

**Issue by S-arige** [googleads/googleads-mobile-android-examples#62]
I want to load our reward ads by admob.
when I have implemented MediationRewardedVideoAdAdapter,but admob sdk don't call my adapter's initialize  method.

class name :com.google.ads.rewardedvideoexample.RewardVideoAdapter
unitId:ca-app-pub-7105356826984861/1863635231

and I set AdMob Network's ecpm to 0.01  and our network is 20.01

**Comment by ericleich** [comment]
Please ask this question on the [Google Mobile Ads SDK developer forum](https://groups.google.com/group/google-admob-ads-sdk). This question is more appropriate for that channel, since the question doesn't relate to one of the samples in this repo.
