### ISSUE TITLE
Advance native ads not loading

### ISSUE THREAD

**Issue by adnanali282** [googleads/googleads-mobile-android-examples#63]
By changing APP_ID and ADS_ID to their own advance ads not loading with giving error, "failed to load ad with error code 0"

**Comment by ericleich** [comment]
Native ads advanced are only available to a limited set of publishers. If you have an account manager, you can reach out them to apply for access.

If you created an ad unit of type "Native" in the AdMob front-end, that ad unit is for [Native Ads Express](https://firebase.google.com/docs/admob/android/native-express).

**Comment by erfindum** [comment]
@ericleich could you share us the details about when will it be out from beta into a release. I have mopub for mediation and it started supporting for google native ads advanced. But why is still google add advanced is in beta from google?
