### ISSUE TITLE
Disruptive ads

### ISSUE THREAD

**Issue by movizeland** [googleads/googleads-mobile-android-examples#630]
hello i faced this problem when i added the open ad code this code that google provide and i received a reject for disruptive ad and i tried to destroye the splashactivity by adding finish(); so to only open the mainactivity when the app run in the background so the open ad only show 1 time when you close the app and when you open it again but when you minimise the app and open it again from the background only show the mainactivity but still receive the reject for disruptive ads i only if this code is provided by google they should fix this problem if any one have a solution the only one i did is to replace the ad idntifier with xxxxxxx so desactivate the ad, and my app only have 1 banner ad not interstitiel not other ads only 1 banner

**Comment by malandr2** [comment]
Hello @movizeland,

This issue appears to be related to app open ands and the Google Play store policy. Please create a new thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) as a next step to adequately address your issue. Closing this out - thanks!
