### ISSUE TITLE
User Messaging Platform UMP Disgraceful idea

### ISSUE THREAD

**Issue by farzadno** [googleads/googleads-mobile-android-examples#635]
Pay attention to this Google AdMob document:

https://developers.google.com/admob/android/privacy

This document says not to request this MobileAds.initialize(this) when you have not obtained user consent. Next, with a simple example (single activity) all advertising requests are dependent on the user's consent. Are applications single activity? All applications have a complex structure that cannot be so easily dependent on everything and waiting for the user's satisfaction. Applications use native ads, banners, etc. in the list of adapters, and all must wait for the user's consent, and MobileAds must be initialized after consent.

Why does Google AdMob see all apps as a single activity?

Why should Google AdMob put the responsibility of user satisfaction on the developer?

Why doesn't Google AdMob automatically handle this consent before initialization in its own SDK?

Mr. Google, apps are so complex and you're putting developers in trouble regardless of the situation :/

**Comment by malandr2** [comment]
Hi @farzadno,

This doesn't appear to be related to our Android samples but rather comments/concerns of the UMP SDK. To adequately address your questions, please create a thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk). Closing out this issue. 

Thanks!
