### ISSUE TITLE
errorCode=3，errMsg=“No fill.”

### ISSUE THREAD

**Issue by xHonghui** [googleads/googleads-mobile-android-examples#637]
I downloaded the official demo(RewardedVideoExample) for testing and used the advertising testing unit provided by the official,
 but received the following error.
2023-12-27 21:25:52.205 16770-16770 MainActivity            com....example.rewardedvideoexample  D  openAdInspector
2023-12-27 21:25:58.273 16770-16770 MainActivity            com....example.rewardedvideoexample  D  load rewarded ad
2023-12-27 21:25:58.274 16770-16770 MainActivity            com....example.rewardedvideoexample  D  isTestDevice = true
2023-12-27 21:25:58.703 16770-16770 MainActivity            com....example.rewardedvideoexample  D  adError = No fill., errorCode = 3
APPLICATION_ID = ca-app-pub-3940256099942544~3347511713
AD_UNIT_ID = ca-app-pub-3940256099942544/5224354917
Is there a corresponding solution for this type of error?
thanks

**Comment by NVentimiglia** [comment]
@xHonghui 

I just tried the sample and everything worked fine on my end. The Ids you provided are also correct.

Generally this type of error is caused by either policy issues or lack of inventory. That said, this is not the case because these are test ad units.

What is your geolocation ?

**Comment by hiddeneyes02** [comment]
@NVentimiglia I am from Algeria and I am having the same issue using sample app with test ads.
Even with VPN from Italy and USA, still getting "No fill" error.
This is not normal for test ads.

**Comment by NVentimiglia** [comment]
A No fill is usually something unrelated to your implementation / code. A no fill is usually a policy issue or a bad ad unit configuration. Please take a look at your admob ui to see if there are any policy errors.

**Comment by hiddeneyes02** [comment]
@NVentimiglia What UI? I am using Google Sample app in this repo with test ads!

**Comment by NVentimiglia** [comment]
@hiddeneyes02 

I am referring to the website where you register your application

https://support.google.com/admob/answer/9989980?visit_id=638417210076463434-429017916&rd=1

**Comment by hiddeneyes02** [comment]
@NVentimiglia I really don't understand what mean my friend.

I am using your sample app (with AdMob **sample app id** "ca-app-pub-3940256099942544~3347511713" and rewarded ad **test**  id "ca-app-pub-3940256099942544/5224354917"). I didn't change a thing in the code, and I certainly not using my app ids.

The link you sent in your last message is talking about how to setup my own app with AdMob ads. What does the Sample Rewarded Test app in this repository have to do with my AdMob account or UI??

**Comment by evgeniy-harchenko** [comment]
Have same issue with VPN. Without - no problem. I think its really depends on your IP address/geography. @hiddeneyes02 is right, this is not normal for test ads.

**Comment by malandr2** [comment]
HI all,

If you are receiving a "no fill" error, to troubleshoot it further please create a new thread in the [Developers Forum](https://groups.google.com/g/google-admob-ads-sdk). This issue is not related to our samples but is more of an ad serving issue, which our samples nor the SDK controls.

Thanks!

**Comment by boudjaninadir** [comment]
> @NVentimiglia I am from Algeria and I am having the same issue using sample app with test ads.
> Even with VPN from Italy and USA, still getting "No fill" error.
> This is not normal for test ads.

Hi 👋 I'm from Algeria and I want to start an app project. However, I'm hesitant because I don't have much experience with AdMob. Is it stable in Algeria, and are there any risks of closure in the future? Please contact me when you have some time. Thank you!

**Comment by boudjaninadir** [comment]
@dzboot02 

Hi 👋 I'm from Algeria and I want to start an app project. However, I'm hesitant because I don't have much experience with AdMob. Is it stable in Algeria, and are there any risks of closure in the future? Please contact me when you have some time. Thank you!
