### ISSUE TITLE
loadAd always fail to load, errorcode 3

### ISSUE THREAD

**Issue by lubeast** [googleads/googleads-mobile-android-examples#64]
Here is my code, i put the `NativeExpressAdView` in a dialog, but it always return error code 3

```java
NativeExpressAdView adView = new NativeExpressAdView(activity);
adView.setAdSize(new AdSize(280, 250));
adView.setAdUnitId("my-ad-unit");
adView.setVideoOptions(new VideoOptions.Builder()
        .setStartMuted(true)
        .build());
 adView.setAdListener(new AdListener() {
          @Override
          public void onAdFailedToLoad(int i) {
                 super.onAdFailedToLoad(i);
          }
});
adLinearLayout.addView(adView);
adView.loadAd(new AdRequest.Builder().addTestDevice("my-device-id").build());
```

`logcat`:

```
03-27 16:30:21.241 21093-21093/com.xxx.xxx I/Ads: Starting ad request.
03-27 16:30:21.618 21093-22617/com.xxx.xxx I/Ads: No fill from ad server.
03-27 16:30:21.619 21093-21093/com.xxx.xxx I/Ads: Scheduling ad refresh 30000 milliseconds from now.
03-27 16:30:21.619 21093-21093/com.xxx.android W/Ads: Failed to load ad: 3
```

But it's working good if i change `adUnitId` to the one in sample project you provided. What may cause this problem???

**Comment by DanteAndroid** [comment]
I face this problem too. This sdk sucks.

**Comment by lubeast** [comment]
@DanteAndroid It seems lots of people have same problem with us but still no a method which can solve it now.  @ericleich Do you have any ideas?

**Comment by ericleich** [comment]
@lubeast How long ago did you create your ad unit? It takes about an hour for a newly created ad unit to start serving ads.

Does the sample ad unit from the [Native Express Example](https://github.com/googleads/googleads-mobile-android-examples/blob/master/admob/NativeExpressExample/app/src/main/res/values/strings.xml#L3) work for you?

**Comment by lubeast** [comment]
Yes, the `Native Express Example` did work for me. Do you mean i should wait at least one hour every time i did some exchange in `Native ads settings`?

**Comment by lubeast** [comment]
I've tested, my `unit id` worked as expected. I think maybe you guys can provide a document that can explain this to developers. Thank you @ericleich 😺

**Comment by ericleich** [comment]
A newly created ad unit will take an hour, but changes to settings should be faster (guessing 10-15 minutes if not sooner).

I have an open feature request against the front-end team to expose this in the front-end, since this is really where this information should be!
