### ISSUE TITLE
Native Advanced Example Fails To Load Ad

### ISSUE THREAD

**Issue by RojS** [googleads/googleads-mobile-android-examples#648]
domain: com.google.android.gms.ads, code: 0, message: Internal error.

![Screenshot_1707839580](https://github.com/googleads/googleads-mobile-android-examples/assets/25417839/cf267c96-941f-40bc-8b1b-ec1a63a2f5bc)

**Comment by NVentimiglia** [comment]
Code: 0 may be due to lack of internet.

That said, please open a case with [SDK Support](https://developers.google.com/admob/support).
