### ISSUE TITLE
Android TV doesn't show banner ads, error code 2, Network error

### ISSUE THREAD

**Issue by kien-ichiisoft** [googleads/googleads-mobile-android-examples#650]
Hey guys,

I run the sample code (AdManager-> Banner example) on Android TV but the banner is not displayed

Here is the response 

`
error: {
                                                                                                      "Code": 2,
                                                                                                      "Message": "Network error.",
                                                                                                      "Domain": "com.google.android.gms.ads",
                                                                                                      "Cause": "null",
                                                                                                      "Response Info": {
                                                                                                        "Response ID": "null",
                                                                                                        "Mediation Adapter Class Name": "",
                                                                                                        "Adapter Responses": [],
                                                                                                        "Response Extras": {}
                                                                                                      }
`                                                                                 

I checked internet connection is working properly

Android TV (Mibox) using android version 9

**Comment by malandr2** [comment]
Hey @kien-ichiisoft, at this time we do not offer support for Android TV. As a result, this may lead to unexpected behavior. If you'd like to file a feature request please do so in the [Developers Forum](https://groups.google.com/g/google-admob-ads-sdk). Thanks!
