### ISSUE TITLE
Getting Error code 3 'No Fill' even when I'm using test ad units

### ISSUE THREAD

**Issue by Rehan2003** [googleads/googleads-mobile-android-examples#651]
Hey there,

I have two apps in the same Admob account and one of them is getting ads normally but another one is not showing a single ad.
My app is published on Play Store and also there is not any issue in Admob dashboard.

I have tried with Test Ad units also but still getting same error. Apart from this I'm also using admob mediation and of course Meta ads are also not showing. Can you help me to fix it ASAP!

**Comment by NVentimiglia** [comment]
No fills can be caused by a number of [different issues](https://support.google.com/admob/answer/9905175)

This may be a product issue more than an SDK implementation or sample issue, please open a ticket with [SDK Support](https://developers.google.com/admob/support).
