### ISSUE TITLE
Compose multiplatform support

### ISSUE THREAD

**Issue by salimisler28** [googleads/googleads-mobile-android-examples#653]
Hello, it would be great if we were able to use good admob in compose multiplatform.

**Comment by NVentimiglia** [comment]
Agreed,

We are looking into Jetpack compose support.

**Comment by PMARZV** [comment]
any eta? this is very critical to have in my opinion....

**Comment by ericleich** [comment]
Planning to add more Jetpack Compose resources in the following months. The example will be iterated on in https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/advanced/JetpackComposeDemo but it's not very useful at this very moment.

To set expectations though, this is just to demonstrate Jetpack Compose in Kotlin Android apps. We are not investigating any [compose multiplatform](https://www.jetbrains.com/lp/compose-multiplatform/) integration.

**Comment by salimisler28** [comment]
That's very sad. Everyone is excited about multiplatform but google. Will you have a development plan for compose multiplatform integration in the future?

**Comment by alfietapping** [comment]
+1 for wanting compose multiplatform support. Flutter has it setup and maintained, would be great to have CMP too.

**Comment by Meet-Miyani** [comment]
> For anyone landing here and still looking for Android + iOS support: I ran into the same gap and ended up building an independent open-source community SDK called **AdMob CMP**.
>
> It wraps the native Google Mobile Ads SDKs behind one Compose Multiplatform API and currently supports:
>
> - Banner
> - Interstitial
> - Rewarded
> - Rewarded interstitial
> - App-open
> - Native ads
>
> The shared Kotlin layer also covers consent-aware initialization, UMP and iOS ATT ordering, ad state and events, caching, full-screen presentation ownership, and native-ad sessions.
>
> It is available from Maven Central as:
>
> ```kotlin
> implementation("dev.avinya.ads:admob-cmp:2.0.0")
> ```
>
> Source, documentation, and sample applications:
>
> https://github.com/Meet-Miyani/admob-compose-multiplatform
>
> This is not an official Google SDK or integration. Applications still configure the required native pieces, including Android manifest metadata, iOS Swift packages and `Info.plist` values, production ad units, consent settings, and store disclosures.
>
> Disclosure: I built and maintain the project. Feedback and reports about real Android or iOS integration cases are very welcome.
