### ISSUE TITLE
Can I initialize MobileAds in both main-processes and sub-processes?

### ISSUE THREAD

**Issue by ChenYiHong930921** [googleads/googleads-mobile-android-examples#654]

**Comment by zeeid** [comment]
yes u can, but recomend only once



Initialize the Google Mobile Ads SDK
Before loading ads, have your app initialize the Google Mobile Ads SDK by calling [MobileAds.initialize()](https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#initialize(android.content.Context,%20com.google.android.gms.ads.initialization.OnInitializationCompleteListener)) which initializes the SDK and calls back a completion listener once initialization is complete, or after a 30-second timeout. This needs to be done only once, ideally at app launch.

[https://developers.google.com/admob/android/quick-start?hl=en](url)

**Comment by NVentimiglia** [comment]
We also have the optimize beta 

https://developers.google.com/admob/android/optimize-initialization
