### ISSUE TITLE
Crash with admob SDK

### ISSUE THREAD

**Issue by DeveloperMobilePersonal** [googleads/googleads-mobile-android-examples#658]
![Screenshot at Mar 20 15-29-48](https://github.com/googleads/googleads-mobile-android-examples/assets/111782554/e2059e46-8f3f-4309-a907-188445859c65)

Since March 18, 2024 firebase has recorded many problems coming from the Admob SDK, I have attached images

**Comment by NVentimiglia** [comment]
Please submit this report to the [SDK team](https://developers.google.com/admob/support).
