### ISSUE TITLE
Native Ad Advance​d 

### ISSUE THREAD

**Issue by erfindum** [googleads/googleads-mobile-android-examples#66]
Hi, could you share us the details about when will Native ad advanced be out from beta into a release. I have mopub for mediation and it started supporting for google native ads advanced. But why is still google add advanced is in beta from google?

**Comment by ericleich** [comment]
I don't have any updates to share about the expansion of Native Ads advanced in AdMob at this time.

MoPub does support AdMob native ads advanced but there is still the requirement that the AdMob account is enabled for the feature.

**Comment by ericleich** [comment]
Also please note that this GitHub repo is for just the sample apps themselves. For more general questions, you can ask them in the Google Mobile Ads SDK [support forum](groups.google.com/group/google-admob-ads-sdk).
