### ISSUE TITLE
on device back button RewardedAd closed. How to keep it 

### ISSUE THREAD

**Issue by RupBarad** [googleads/googleads-mobile-android-examples#665]
on device back button RewardedAd closed. How to keep it 

Steps:
- on page Initalize SDK then load it 
-  After load on button press show RewardedAd
    REF: https://developers.google.com/admob/android/rewarded
- On physical back button Ad closed not keep there

Expected: It should remain until reward earn. back button should not work for this

could you please guide me

Note: Already use alert before show the advertise

**Comment by NVentimiglia** [comment]
If the back button is not appearing it may be a bad creative. You will need to raise the issue with [the SDK team here](https://developers.google.com/admob/support).
