### ISSUE TITLE
App open ads code not pasing Google play store inspection.

### ISSUE THREAD

**Issue by bojanxxx** [googleads/googleads-mobile-android-examples#666]
When I use your example of app open ads i got rejected from Google play store. I have this problem with multiple aplication. I was forced to remove app open ads from all  my apps and now they are published.

App Status: Rejected
Your app has been rejected and wasn't published due to the policy issue(s) listed below. If you submitted an update, the previous version of your app is still available on Google Play.

Issue found: Disruptive Ads

**Comment by NVentimiglia** [comment]
@bojanxxx 

Can you open a [case here](https://developers.google.com/admob/support)? This issue tracker is intended for fixes to the sample app, but this is a policy issue and will need to be directed to the policy team.
