### ISSUE TITLE
here was a problem getting an ad response. ErrorCode: 0(ApLovin)

### ISSUE THREAD

**Issue by hamidrv** [googleads/googleads-mobile-android-examples#71]
04-17 10:57:40.925 8129-8129/com.myproject.addmob I/Ads: Starting ad request.
04-17 10:57:40.951 8129-8129/com.myproject.addmob W/Ads: The reward video has not loaded.
04-17 10:57:40.954 8129-8263/com.myproject.addmob V/FA: Connection attempt already in progress
04-17 10:57:40.960 8129-8335/com.myproject.addmob I/WebViewFactory: Loading com.google.android.webview version 57.0.2987.132 (code 298713200)
04-17 10:57:40.966 8129-8263/com.myproject.addmob V/FA: Activity resumed, time: 266012127
04-17 10:57:40.977 8129-8352/com.myproject.addmob D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-17 10:57:41.052 8129-8329/com.myproject.addmob W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
04-17 10:57:41.123 8129-8352/com.myproject.addmob I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
04-17 10:57:41.173 8129-8352/com.myproject.addmob I/OpenGLRenderer: Initialized EGL, version 1.4
04-17 10:57:41.246 8129-8329/com.myproject.addmob I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
04-17 10:57:41.246 8129-8143/com.myproject.addmob I/art: Background sticky concurrent mark sweep GC freed 32691(4MB) AllocSpace objects, 37(1856KB) LOS objects, 21% free, 19MB/25MB, paused 4.874ms total 107.962ms
04-17 10:57:41.284 8129-8335/com.myproject.addmob I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
04-17 10:57:41.284 8129-8335/com.myproject.addmob I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
04-17 10:57:41.290 8129-8335/com.myproject.addmob I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
04-17 10:57:41.290 8129-8335/com.myproject.addmob I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
04-17 10:57:41.298 8129-8335/com.myproject.addmob I/cr_LibraryLoader: Time to load native libraries: 1 ms (timestamps 5878-5879)
04-17 10:57:41.309 8129-8263/com.myproject.addmob V/FA: Processing queued up service tasks: 6
04-17 10:57:41.384 8129-8335/com.myproject.addmob I/chromium: [INFO:library_loader_hooks.cc(163)] Chromium logging enabled: level = 0, default verbosity = 0
04-17 10:57:41.385 8129-8335/com.myproject.addmob I/cr_LibraryLoader: Expected native library version number "57.0.2987.132", actual native library version number "57.0.2987.132"
04-17 10:57:43.102 8129-8202/com.myproject.addmob W/Ads: There was a problem getting an ad **response. ErrorCode: 0
04-17 10:57:43.106 8129-8129/com.myproject.addmob W/Ads: Failed to load ad: 0**

**Comment by ericleich** [comment]
Looks the same as Issue #68 . Please share logs again with verbose output as explained in #68 , and add them to that issue.
