### ISSUE TITLE
Bug: FullScreenNativeExample just shows some desert video, without any other Views 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-examples#718]
This is all I can see on this sample when running it, no app-icon, no buttons, no texts...:

https://github.com/googleads/googleads-mobile-android-examples/tree/main/java/admob/FullScreenNativeExample

![image](https://github.com/googleads/googleads-mobile-android-examples/assets/5357526/4088652a-083e-4596-ac7b-9972570cf434)

Looking at the layout, I'm not sure but I think the app-icon seems to be located in a weird place, too:

![image](https://github.com/googleads/googleads-mobile-android-examples/assets/5357526/b566a2cf-53b1-4e9a-add8-34a465311aa7)
 
```
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.media3:media3-exoplayer:1.3.1'
    implementation 'androidx.media3:media3-exoplayer-dash:1.3.1'
    implementation 'androidx.media3:media3-ui:1.3.1'
    implementation 'androidx.media3:media3-session:1.3.1'
    implementation 'com.google.android.gms:play-services-ads:23.2.0'
    implementation 'androidx.media3:media3-common:1.3.1'
```

**Comment by s-kachroo** [comment]
Hey, try scrolling down since its a recyclerView. You will observe the test ad (provided your setup is correct)

**Comment by AndroidDeveloperLB** [comment]
@s-kachroo Why would a full screen ad be in a RecyclerView? Doesn't make sense. Users won't know they need to scroll down in a video that is shown in full screen, let alone when there is no clue about it  (such as a scrollbar).
What is the purpose of it being in a RecyclerView?

I've tested it now, and seems you are correct, but it causes it to be very slow and shows the issue I've written of, of the icon in a weird place. Also shows the validator window multiple times, sometimes even being cut in the screen.

![image](https://github.com/googleads/googleads-mobile-android-examples/assets/5357526/b6649874-a6f5-465b-a72e-5ac3fdbce613)

Such a weird sample...
At least I know that it should work, when used better...
