### ISSUE TITLE
Failed to load ads dynamite module

### ISSUE THREAD

**Issue by martincz** [googleads/googleads-mobile-android-examples#72]
I used admob sdk in a system app, play service is 10.5.48, but no ad display .

dependencies in Android.mk:
LOCAL_STATIC_JAVA_AAR_LIBRARIES := \
    play-services-ads \
    play-services-ads-lite \
    play-services-base \
    play-services-basement

when I exec 'adb shell setenforce 0', ad is displayed.
I already try update sepolicy config in system_app.te but not work too.
allow system_app app_data_file:dir search;

Can you help me?

**Here is logcat:**
04-20 20:23:53.925  4713  4713 W om.mokee.center: type=1400 audit(0.0:82): avc: denied { search } for name="com.google.android.gms" dev="mmcblk0p28" ino=41220 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
04-20 20:23:53.925  4713  4713 W om.mokee.center: type=1400 audit(0.0:83): avc: denied { search } for name="com.google.android.gms" dev="mmcblk0p28" ino=41220 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
04-20 20:23:53.925  4713  4713 W om.mokee.center: type=1400 audit(0.0:84): avc: denied { search } for name="com.google.android.gms" dev="mmcblk0p28" ino=41220 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
04-20 20:23:53.926  4713  4713 W FileUtils: Failed to chmod(/data/user/0/com.google.android.gms/app_chimera): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
04-20 20:23:53.927  4713  4713 E ChimeraCfgMgr: Failed to read module config: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/app_chimera/current_config.pb (Permission denied)
04-20 20:23:53.927  4713  4713 W DynamiteUtils: Failed to load module: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/app_chimera/current_config.pb (Permission denied)
04-20 20:23:53.927  4713  4713 W DynamiteUtils: Attempt 3 failed.
04-20 20:23:53.928  4713  4713 W FileUtils: Failed to chmod(/data/user_de/0/com.google.android.gms/app_chimera): android.system.ErrnoException: chmod failed: EACCES (Permission denied)
04-20 20:23:53.929  4713  4713 W DynamiteUtils: Client module failure reason: 1
04-20 20:23:53.930  4713  4713 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1357 android.content.ContextWrapper.startService:613 com.google.android.gms.chimera.container.FileApkIntentOperation.b:93 jln.a:1045 jlp.a:3046 
04-20 20:23:53.933  4713  4713 D DynamitePackage: Module could not be loaded.
04-20 20:23:53.935  4713  4713 E DynamitePackage: Failed to load ads dynamite module.
04-20 20:23:53.935  4713  4713 E DynamitePackage: android.os.RemoteException
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at dca.<init>(:com.google.android.gms:37)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at dca.a(:com.google.android.gms:23)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.ads.AdManagerCreatorImpl.newAdManagerByType(:com.google.android.gms:86)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.ads.internal.client.n.onTransact(:com.google.android.gms:91)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.os.Binder.transact(Binder.java:499)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzeu$zza$zza.zza(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzeb.zza(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzek$3.zzeI(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzek$3.zzeJ(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzek$zza.zzeR(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzek.zza(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzek.zzb(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzfg.zzS(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.internal.zzfg.zza(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.google.android.gms.ads.InterstitialAd.loadAd(Unknown)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.mokee.center.fragments.MoKeeUpdaterFragment.requestNewInterstitial(MoKeeUpdaterFragment.java:312)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.mokee.center.fragments.MoKeeUpdaterFragment.onCreate(MoKeeUpdaterFragment.java:306)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.app.Fragment.performCreate(Fragment.java:2075)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1060)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.app.BackStackRecord.setLastIn(BackStackRecord.java:838)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.app.BackStackRecord.calculateFragments(BackStackRecord.java:861)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:719)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.View.measure(View.java:19861)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:704)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:774)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.View.measure(View.java:19861)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.View.measure(View.java:19861)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.View.measure(View.java:19861)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.View.measure(View.java:19861)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.View.measure(View.java:19861)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:690)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.View.measure(View.java:19861)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.os.Handler.handleCallback(Handler.java:751)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.os.Looper.loop(Looper.java:154)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at android.app.ActivityThread.main(ActivityThread.java:6178)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
04-20 20:23:53.935  4713  4713 E DynamitePackage: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
04-20 20:23:53.935  4713  4713 D DynamitePackage: Instantiated singleton DynamitePackage.
04-20 20:23:53.944  4713  4713 E Ads     : This app is using a lightweight version of the Google Mobile Ads SDK that requires the latest Google Play services to be installed, but Google Play services is either missing or out of date.

**Comment by ericleich** [comment]
Please reach out to the [google-mobile-ads-sdk](https://groups.google.com/group/google-admob-ads-sdk) forum for support. This issue does not look related to the sample apps.
