### ISSUE TITLE
Native ad Video controller stop method is not working

### ISSUE THREAD

**Issue by abd3lraouf** [googleads/googleads-mobile-android-examples#725]
At some Point, I want to trigger the stop method on the video controller of the native ad, but it's not working at all. I want to reset the playback of the video itself, so that when it's played back again it will be starting from the beginning

**Comment by NVentimiglia** [comment]
Access to Custom playback controls is limited. To request access [reach out to your account manager](https://admob.google.com/home/request-consult/).
