### ISSUE TITLE
BannerExample: Changing adSize to SMART_BANNER gives Failed to load ad: 3 on landscape

### ISSUE THREAD

**Issue by nopakos** [googleads/googleads-mobile-android-examples#73]
Hello,
Just changing `ads:adSize="BANNER"` to `ads:adSize="SMART_BANNER"` does not load the example dfp_example_ad giving a `"No fill from ad server."` and `"Failed to load ad: 3"` when device is in landscape.
The same happens with "real" live ads from DFP but not from ads from AdMob.
This happens on the emulator and real devices.
Thanks.

**Comment by ericleich** [comment]
Hi @nopakos 

See the [documentation](https://developers.google.com/mobile-ads-sdk/docs/dfp/android/banner#smart_banners) for smart banner. In landscape on a phone, the ad is going to be 32dp height. The DFP sample ad unit doesn't have a 32dp height ad trafficked to it, so that's why DFP smart banner doesn't work. The AdMob sample ad is a text ad that can fit any size, so that's why it still returns.

**Comment by nopakos** [comment]
Hi,
Thank you for your reply.
1. On a Nexus 6P, the DFP example smart banner requests a 50dp height ad, I think, and still a "No fill from ad server" is returned from the DFP example smart banner.
2. Using an AdMob Unit Id directly, with images only ad type selected, is working fine in landscape.
3. With real DFP ads there is no fill for landscape ads. Maybe I have not set the line-items sizes correctly or something else is going on?

**Comment by ericleich** [comment]
1. You're right, Nexus 6P is wide enough that in landscape it is requesting 50dp height. Looks like a 690x50 request. The sample DFP ad unit is only set up for 320x50 and is only targeted to a 320x50 line item. My experience in the past has been that as long as the height matched up (i.e. 50), the width could be smaller and DFP would still match it. Perhaps there is a limit on how much smaller the ad could be. 320 is less than half of 690, so maybe 50% is that threshold.
2. DFP reservations are very specific about the line item size matching the request size. Smart banner is kind of an exception where it is a little flexible. AdMob doesn't have this size requirement, is able to take an image, and put some padding on the sides to make a 690x50 work.
3. If you are trying to make reservations work, you can try making the line item support a wider size (e.g. 480x50) and either create a 480x50 ad or use a size override in DFP to make the 320x50 ad support a 480x50 size as well.

**Comment by nopakos** [comment]
Sorry for the late answer. I've trying the suggestions but I could not make DFP work for landscape on Android. On iOS everything seems to work. I've switched back to AdMob on Android. Thank you for your help!
