### ISSUE TITLE
 Google User Messaging Platform (UMP) SDK : Need to know About Admob Consent Dialog adding menu button is required like user can edit later?

### ISSUE THREAD

**Issue by muhammadarslannasr** [googleads/googleads-mobile-android-examples#742]
if required then can i add within three doted when user press menu open and can press on text like change consent something?

Need to know about this, also in Admob there are three Consent.

1- EUU 
2- American states
3- Brazil 

Need to set for all as American states not allowing to save and for brazil there is no concent how can integrate that?

Using The Google User Messaging Platform (UMP) SDK

**Comment by malandr2** [comment]
Hi @muhammadarslannasr, we can address your question in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk). Please create a new thread so we can begin the troubleshooting process. Closing this out - thanks!
