### ISSUE TITLE
these is a crash for admob 23.0.0 and 22.6.0

### ISSUE THREAD

**Issue by yangguanglu** [googleads/googleads-mobile-android-examples#744]
we just used some test devices to run monkey test,then it happened.

08-07 21:45:38.944594 13395 13395 E AndroidRuntime: FATAL EXCEPTION: main
08-07 21:45:38.944594 13395 13395 E AndroidRuntime: Process: com.demo.mediation, PID: 13395
08-07 21:45:38.944594 13395 13395 E AndroidRuntime: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at android.view.ViewGroup.addViewInner(ViewGroup.java:5368)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at android.view.ViewGroup.addView(ViewGroup.java:5188)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at android.view.ViewGroup.addView(ViewGroup.java:5128)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at android.view.ViewGroup.addView(ViewGroup.java:5100)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at com.google.android.gms.ads.internal.mraid.f.b(:com.google.android.gms.policy_ads_fdr_dynamite@242402503@242402501034.640994647.640994647:30)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at com.google.android.gms.ads.internal.mraid.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@242402503@242402501034.640994647.640994647:47)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at com.google.android.gms.ads.internal.webview.r.d(:com.google.android.gms.policy_ads_fdr_dynamite@242402503@242402501034.640994647.640994647:52)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at com.google.android.gms.ads.internal.webview.ai.destroy(:com.google.android.gms.policy_ads_fdr_dynamite@242402503@242402501034.640994647.640994647:34)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at com.google.android.gms.ads.internal.webview.x.run(:com.google.android.gms.policy_ads_fdr_dynamite@242402503@242402501034.640994647.640994647:3)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at android.os.Handler.handleCallback(Handler.java:938)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at android.os.Handler.dispatchMessage(Handler.java:99)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at m.bbg.a(:com.google.android.gms.policy_ads_fdr_dynamite@242402503@242402501034.640994647.640994647:1)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@242402503@242402501034.640994647.640994647:1)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at m.bbg.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@242402503@242402501034.640994647.640994647:1)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at android.os.Looper.loop(Looper.java:268)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at android.app.ActivityThread.main(ActivityThread.java:8088)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at java.lang.reflect.Method.invoke(Native Method)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
08-07 21:45:38.944594 13395 13395 E AndroidRuntime:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

**Comment by yangguanglu** [comment]
fix by add logic to remove banner view from its parent.

**Comment by xiaxiaxiaxia** [comment]
The Google Ads team said that the issue has been fixed in the subsequent version, but it still crashes occasionally on my end.
