### ISSUE TITLE
error: incompatible types

### ISSUE THREAD

**Issue by sumbganesh** [googleads/googleads-mobile-android-examples#75]
I am trying to implement native ads in RecyclerView by following Admob garage tutorial. But I am getting error saying "error: incompatible types: WallpaperViewHolder cannot be converted to WallpaperAdapter.NativeExpressAdViewHolder" and "error: incompatible types: Hit cannot be converted to NativeExpressAdView" in onBindViewHolder

**Comment by ericleich** [comment]
I recommend you take download and try out the [NativeExpressRecyclerViewExample](https://github.com/googleads/googleads-mobile-android-examples/tree/master/advanced/NativeExpressRecyclerViewExample) that's on this repo, and work backwards from there.

My guess is that your `getItemViewType` method isn't returning the correct view type in some cases, and so your casts are failing. [Here](https://github.com/googleads/googleads-mobile-android-examples/blob/master/advanced/NativeExpressRecyclerViewExample/app/src/main/java/com/google/android/gms/example/nativeexpressrecyclerviewexample/RecyclerViewAdapter.java#L82-L85) is the implementation of that method from the example I mentioned above.

**Comment by sumbganesh** [comment]
Here you can see the activitie.
Stackoverflow.com/questions/44093613

**Comment by ericleich** [comment]
Answered on Stackoverflow.

**Comment by sumbganesh** [comment]
I have solved the NativeExpressAdViewHolder , I used wallpaperViewHolder instead Recycle.ViewHolder. But second one is still having problem in casting. I can't understand what is wrong. I have updated the code. Please check the question here https://stackoverflow.com/questions/44093613/error-incompatible-types-cannot-be-converted-to-in-recyclerview.
