### ISSUE TITLE
Bug: keep getting error 13 (no-fill) for test ads (rewarded video example)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-examples#758]
This:

https://groups.google.com/g/google-admob-ads-sdk/c/lKWjM-UDnW8

I don't know where to put it, because it's about Admob itself not providing ads of the simplest form, of test ads...

**Comment by malandr2** [comment]
Hi @AndroidDeveloperLB, I see you've created an issue in the AdMob Developers forum. That is the correct place for us to triage your issue. Closing this one out - thanks!
