### ISSUE TITLE
Why Activity destroying while reward ad video opens ?

### ISSUE THREAD

**Issue by devsideal** [googleads/googleads-mobile-android-examples#77]
I want to update my UI onRewardedVideoAdClosed() if user Rewarded , but unable to update any view of my activity due to activity is destroying while reward ad video opens,
I'm doing anything wrong ?

**Comment by ericleich** [comment]
The rewarded video ad presents in a new activity. Does your app destroy the activity when a new one gets presented, such as using any of the methods listed in [this StackOverflow post](https://stackoverflow.com/questions/2550099/how-to-kill-an-android-activity-when-leaving-it-so-that-it-cannot-be-accessed-fr)?

**Comment by devsideal** [comment]
I got the issue and fixed it now, i forgot to add android:configChanges="orientation|screenSize"  in my activity , by adding this property solve my issue.
