### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by wwq006** [googleads/googleads-mobile-android-examples#80]
why:
com.google.android.gms.ads.AdActivity requires the android:configChanges value to contain "keyboardHidden"

**Comment by ericleich** [comment]
https://developer.android.com/guide/topics/resources/runtime-changes.html#HandlingTheChange

If the keyboard availability changes and an ad is showing in the AdActivity, the Google Mobile Ads SDK doesn't want that AdActivity to restart.

Note: Please post future support questions like this to the [Google Mobile Ads SDK developer forum](groups.google.com/group/google-admob-ads-sdk). The goal of this issue tracker is to track issues with the Android sample apps in this repository.
