### ISSUE TITLE
Advanced Native Ad won't show

### ISSUE THREAD

**Issue by billrancho** [googleads/googleads-mobile-android-examples#81]
I tried to enable Native Ad with those keys, but it keeps saying that 
"There was a problem getting an ad response. ErrorCode: 0
Failed to load ad: 0"
It ran well with AdRequest.Builder.addTestDevice("XXXXXX") 
I am guessing that my ad need to be reviewed as it has just been created. 
But the thing is where can I find its review status?
In case it wasn't because of reviewing stuff , what can possibly be the problem?

**Comment by ericleich** [comment]
Native Ads Advanced is currently only available to a limited set of publishers. You would have to ask your account manager (if you have one) to be enabled.
