### ISSUE TITLE
Error code : 0 - Native Express Ad

### ISSUE THREAD

**Issue by meet2011** [googleads/googleads-mobile-android-examples#87]
I'm trying to show Native Express Ad but it always shows error code 0. I've also tried sample Ad Unit ID but result is the same.

Please have a look.

_Sample Ad Unit ID :_ **ca-app-pub-3940256099942544/2177258514**
_My Ad Unit ID :_ **ca-app-pub-1785203981199275/4830571118**

 **XML** 

>     <?xml version="1.0" encoding="utf-8"?>
>     <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:ads="http://schemas.android.com/apk/res-auto"
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content"
>     android:orientation="vertical">
> 
>     <com.google.android.gms.ads.NativeExpressAdView
>         android:id="@+id/nativeAd"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         ads:adSize="360x100"
>         ads:adUnitId="@string/native_ad_unit_id" />
> 
>     </LinearLayout>

**Code**
>         NativeExpressAdView nativeExpressAdView = findViewById(R.id.nativeAd);
> 
>     //  AdRequest adRequest = new AdRequest.Builder().addTestDevice("56858C2DBF1F3D6CE71464713A71D97B").build();
>         AdRequest adRequest = new AdRequest.Builder().build();
> 
>         Log.d(TAG, "Test Device :" + adRequest.isTestDevice(this));
>         nativeExpressAdView.loadAd(adRequest);
> 
>         nativeExpressAdView.setAdListener(new AdListener() {
> 
>             @Override
>             public void onAdLoaded() {
>                 // Code to be executed when an ad finishes loading.
>                 Log.i(TAG, "onAdLoaded");
>             }
> 
>             @Override
>             public void onAdFailedToLoad(int errorCode) {
>                 // Code to be executed when an ad request fails.
>                 Log.i(TAG, "onAdFailedToLoad with error code :" + errorCode);
>             }
> 
>             @Override
>             public void onAdOpened() {
>                 // Code to be executed when the ad is displayed.
>                 Log.i(TAG, "onAdOpened");
>             }
> 
>             @Override
>             public void onAdLeftApplication() {
>                 // Code to be executed when the user has left the app.
>                 Log.i(TAG, "onAdLeftApplication");
>             }
> 
>             @Override
>             public void onAdClosed() {
>                 // Code to be executed when when the interstitial ad is closed.
>                 Log.i(TAG, "onAdClosed");
>             }
> 
>         });
>

**Comment by stowy** [comment]
hi @meet2011 thanks for the question. These issues are primarily for issues with the example apps however, I would request that you post your question to the admob support forum - https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they can help you trouble shoot this.

However, I checked your ad ID and it was working correctly, though you do have to check the ad size is correct. Another thing is it takes some time after setting the ad up for it to register, so I would suggest retrying.
