### ISSUE TITLE
AdMob causing OOM when the url is too large

### ISSUE THREAD

**Issue by ParkerK** [googleads/googleads-mobile-android-examples#88]
I'm finding some users are crashing when I try to load a NativeExpressAd. The stack traces, and this SO link make it seem that it's happening because advertisers are providing exceedingly long URLs full of tracking info, and it crashes chromium:  https://stackoverflow.com/questions/45573920/a-lot-of-outofmemoryerror-from-samsung-galaxy-devices-on-android-7-x

This is on GoogleAds sdk 11.2

> java.lang.StringFactory.newStringFromChars (StringFactory.java)
java.lang.StringFactory.newStringFromChars (StringFactory.java:218)
java.lang.StringFactory.newStringFromBytes (StringFactory.java:203)
java.lang.StringFactory.newStringFromBytes (StringFactory.java:63)
android.util.Base64.encodeToString (Base64.java:456)
org.chromium.android_webview.AwContents.loadDataWithBaseURL (AwContents.java:430)
com.android.webview.chromium.WebViewChromium.loadDataWithBaseURL (WebViewChromium.java:188)
android.webkit.WebView.loadDataWithBaseURL (WebView.java:992)
com.google.android.gms.ads.internal.webview.p.loadDataWithBaseURL (p.java:131)
com.google.android.gms.ads.internal.webview.o.loadDataWithBaseURL (o.java:104)
com.google.android.gms.ads.internal.renderer.i.a (i.java:8)
com.google.android.gms.ads.internal.renderer.a.c (a.java:35)
com.google.android.gms.ads.internal.renderer.g.a (g.java:11)
com.google.android.gms.ads.internal.zzaj.run (zzaj.java:28)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7224)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Comment by stowy** [comment]
Hi @ParkerK - thanks for the question. For this type of question (not specific to the sample apps code in this repro), can I request you post the question to our support forum - https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - as it seems like an issue with the SDK, and they will be able to help debug and pass on to our engineers as needed. 

Thanks,

Sam
