### ISSUE TITLE
ad dmob don t show 

### ISSUE THREAD

**Issue by gamergamer5550** [googleads/googleads-mobile-android-examples#89]
hi can you help me .when i open my app ad admob don t show but ad admob test show what should i do

**Comment by aataprian** [comment]
Yes of course I will do it while I can why not
		
		

		Dapatkan Outlook untuk iOS
	




On Thu, Aug 24, 2017 at 9:26 AM +0700, "gamergamer5550" <notifications@github.com> wrote:












hi can you help me .when i open my app ad admob don t show but ad admob test show what should i do

**Comment by stowy** [comment]
hi @gamergamer5550 - can I request you please post your question on our support forum at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android, they will be able to help you troubleshoot your issue.

It could be an issue with your ad unit, you need to make sure the parameters (such as size) match up to the request you are making. There is also a delay in propogation from when you first create your ad unit to when it will start successfully serving ad requests, so if it is a new ad unit, you may need to wait some time and try again.

Thanks,

Sam
