### ISSUE TITLE
Receiving Errorcode: 0 after publish for devices

### ISSUE THREAD

**Issue by fatihkiymet** [googleads/googleads-mobile-android-examples#90]
Followed the instructions for Native Ad Advance, everything was fine till publishing app for real devices

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our support forum at https://groups.google.com/forum/#!forum/google-admob-ads-sdk - they will be able to help debug your issue with you efficiently.

I recommend you provide some more detail, it sounds to me that it may be that your ad unit may not be live yet.
