### ISSUE TITLE
Native Content Ads failing to load with error code 0

### ISSUE THREAD

**Issue by kabir4691** [googleads/googleads-mobile-android-examples#91]
I am implementing both interstitial and native Admob ads in my Android application. The interstitial ads are loading without any problem. The native ads also used to load fine till some time back. Now, each time I request for a Native Content Ad, the requests fail with the error code 0. Following is the logcat response for the same:

09-06 14:29:05.310 31873-31488/? W/Ads: Received error HTTP response code: 403
09-06 14:29:05.311 30332-30342/? W/Ads: There was a problem getting an ad response. ErrorCode: 0
09-06 14:29:05.312 30332-30332/? W/Ads: Failed to load ad: 0 

My ad unit ID is : ca-app-pub-3437037697104306/8636178082

I have tried implementing it in the sample code provided by you too. The response is the same. 

Please look into this and advise on how to proceed further.

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our support forum at https://groups.google.com/forum/#!forum/google-admob-ads-sdk - they will be able to help debug your issue with you efficiently.
