### ISSUE TITLE
Avoid Loading the NativeExpressAdView at zero index of recyclerview 

### ISSUE THREAD

**Issue by shobhan1595** [googleads/googleads-mobile-android-examples#92]
when am restricting the NativeExpressAdView in the Zero position am getting casting exceptions in adapter . please help me out to solve this problem

**Comment by stowy** [comment]
Hi @shobhan1595, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
