### ISSUE TITLE
Error getting in cardView for few devices.

### ISSUE THREAD

**Issue by akhileshAwasthi** [googleads/googleads-mobile-android-examples#93]
The following line sometimes generates a crash when we try to load an ad inside a RecyclerView within a Fragment. I tried all possible ways of getting the cardView (includes inflating the container view) but each attempt ended without much success. Any other way possible to do so ??
 
https://github.com/googleads/googleads-mobile-android-examples/blob/eaf81e9769e4d78d621d66c6f9a60c4fa04c09c3/advanced/NativeExpressRecyclerViewExample/app/src/main/java/com/google/android/gms/example/nativeexpressrecyclerviewexample/MainActivity.java#L105

**Comment by stowy** [comment]
Hi, which device types are you seeing this issue on? Can you reproduce in an emulator?

**Comment by akhileshAwasthi** [comment]
It is seen in devices below lollipop. I have tried this with both real device and emulator.

**Comment by stowy** [comment]
Closing for now as unable to repro. If you have more specific details to reproduce in test example please advise. Alternatively, for support debugging your apps, you can make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors / exceptions being seen and code showing how to reproduce the problem.
