### ISSUE TITLE
hello, the link of Native ListView is 404, please help

### ISSUE THREAD

**Issue by cqswxj2013** [googleads/googleads-mobile-android-examples#94]
Native ListView - Provides an example for displaying ads from DFP Custom Rendering in a ListView.

**Comment by RedBrogdon** [comment]
You're right. We reconfigured the directory structure for the samples so we could introduce Kotlin support, which broke our README. An update's just waiting on final internal review.

In the meantime, you can find the Native ListView example here:

https://github.com/googleads/googleads-mobile-android-examples/tree/master/java/advanced/NativeListViewExample
