### ISSUE TITLE
Hello, how can i know that advertising has been reported to admob server after the ad loaded, in other words, how do I know that the advertising showing is effective for me to get a profit? please help.

### ISSUE THREAD

**Issue by cqswxj2013** [googleads/googleads-mobile-android-examples#95]
i am a Chinese, my words maybe not very well, excuse me.

**Comment by betaninboydesenvolvimento** [comment]
Hi I have the same problem, I've put a reward video between activities but
when it finishes don't pay to me..

**Comment by RedBrogdon** [comment]
The SDK will record impressions (when an ad is shown to a user) and clicks for ads automatically and report them to the server as appropriate. You can see the results in [AdMob's reports](https://support.google.com/admob/answer/2751663). Typically it takes a good bit of traffic (thousands of impressions) for the numbers to start to stabilize.
