### ISSUE TITLE
There was a problem getting an ad response. ErrorCode: 0

### ISSUE THREAD

**Issue by poikl369** [googleads/googleads-mobile-android-examples#96]
AdRequestServiceImpl: Sending request: https://googleads.g.doubleclick.net/mads/gma?riv=5&_activity_context=true&format=300x300_as&gl=CN&seq_num=1&eid=318475406%2C318476782%2C318478606%2C46621102&u_sd=3.5&ms=CpgECoACwEBb0xwIeWYsimPsd50qGbZBDhkbl8h9ON0QLDLSZbcKmu9kbgWWF74YSOs5WVUGwnzx0Sn7aeAdRJzJSm8lmhRfd0w2NjCL3gCeB3cAncA4miQtXvxmsDLcop3FmUPSto-i79vr23LCwvXuiQG3yfT0BmTSbTNACV6G5DFxwaf_4K9KluQzzR1Xcn0D2hNCmRGwFfVh45D1J-pcfp0eOSlNA8Gdv3JvMzRLEDHPKhmZGqnLwzpqDjjGB0UIBZ2IakY_jMXhhUZ3TygqIrMifpo8Je_BFBYYD9w0iKj4-_SGD6aCQb58AtMWeIJ-L9PQ4avJQ3rei1kBRN8ig42yxQqAAvGvf980bkF7RXmVzZ2-BaS88VqyG7Ax2ebsyfCgDRpTsBnv1UF6gqfDFGfPBAtA1Okx3A_qU6uOGHd4Wxe9U-o6P8CWUs4yLoQZiAAv1ajWGCB0OQmgBPZwyXNlNbqhsI9joRGBmMJu9Wylu7s7jmRAhk9gZlUzgUP-B8-GtlWpFHctKLq5ydM2At6aGsVmcfTl5tiV4I5TCDkuRdeEH01bGErpFHKSgTwbg1qxSYnaN9nNoHBPhSiJowuq9A4_x9s7yKcFBef1tXxEHL7E0-Hv6KyKGk5Tl2-maADWYOoxyaauxPtmNM83mu911gWEleQHg0c7fok6gafjTvHVs_oSEBqwypIDAo00GPu64pUc4dkSlQIKgAJHX2hKX0Digb71YZzPQG_ZBxvKqYWvQAZkWgC4c08Gyr9dPMzrD0DBnTWHWBdnNVLBwrYdWp-jGpyZGY8wuFZc4p0gS01BSsS-DoX_tsSwuXPDCvCu3dseUniuWPcXrZGPSzklVx5DVwKT01qYEQyzJuFKiqiE6jNAAsx0wRJVtpNNgtS3eMboy93wxR7gQni2h98gxIXOunzX_Dnhi6kmo3WxtQVQ88Vk4LwtfQLrtNIW5jUzehETO-bTZY4PQJiIi2M0BwnlrFs62POBOw51XbcTnByiFfQ_BRD__jvke_0PZyU3CFjoSkLufT3cs3juQI3cbl4Fa7F8QxK10iFCEhCnudTAfWL75noDYwbwicC8&target_api=26&hl=zh-CN&scroll_index=-1&platform=Huawei&submodel=Nexus%206P&rm=2&android_app_muted=false&request_id=eccb3667-c8f6-437f-9a15-e764f66b34fc&am=0&ma=0&cnt=1&js=afma-sdk-a-v11021010.11021010.0&session_id=2821117920154105955&muv=7&ene=true&coh=1&sp=0&gnt=0&mv=80834100.com.android.vending&android_app_volume=1&android_num_video_cache_tasks=0&is_test_device=true&adtest=on&u_w=412&u_h=684&msid=com.ly.freemusic&app_name=37.android.com.ly.freemusic&_package_name=com.ly.freemusic&an=37.android.com.ly.freemusic&net=wi&u_audio=1&u_so=p&basets=116990868&currts=116990868&preqs_in_session=2&pclick=0&support_transparent_background=true&pimp=0&preqs=0&time_in_session=273308&output=html&region=mobile_app&u_tz=480&client_sdk=1&ex=1&client=ca-app-pub-1657150536917944&slotname=1343467886&gsb=wi&local_service=false&lite=false&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_sfv_dinm_dim_nav_navc_dinmo&bisch=true&blev=0.94&swdr=false&cans=5&canm=false&ibctc=true&_mv=25.android&pscfas=true&heap_free=808514&heap_max=536870912&heap_total=11844546&wv_count=0&sai=0&mr=1141485994923993463%2C1828993502439758578%2C-2587974151784988998%2C-4933320001752770929%2C-6888578061511961183&blockAutoClicks=true&forceHttps=true&includeDoritos=true&content_infol=11&blob=ABPQqLF32mrSeZ_iuPBTVA-DwEud3T-7w8fjceIOyQRlpkRgBm8IINhhE4hQuhLlol9LOuIm8oIqiMOflRlakC6HiDkUUuui0Z0TNfveFKYq17ROev07P700w5lDEdVhfVyQQK9zQOqP-wcqeIaueGbC-f93OFUN8RgY_soHTRC7JkXU7ADmhBO5LI8y2it1987lbad949zeHpqW2kbfOR4LS3eQRtVBRZng_7q6UqMoIF9-bpVcmFDnF3Dl5ZuC39QswnQW7vOft8xrasE&et=2&tcar=4&jsv=4-production-20171031_RC00&urll=2915#_activity_context=true&android_num_video_cache_tasks=0&caps=inlineVideo_interactiveVideo_mraid1_mraid2_sdkVideo_th_autoplay_mediation_av_transparentBackground_sdkAdmobApiForAds_di_sfv_dinm_dim_nav_navc_dinmo&eid=318475406%252C318476782%252C318478606%252C46621102&format=300x300_as&heap_free=808514&heap_max=536870912&heap_total=11844546&js=afma-sdk-a-v11021010.11021010.0&mr=1141485994923993463%252C1828993502439758578%252C-2587974151784988998%252C-4933320001752770929%252C-6888578061511961183&msid=com.ly.freemusic&preqs=0&scroll_index=-1&seq_num=1&target_api=26

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.

In this case, it is quite possible that if you are using a new ad Unit ID, that it has not propagated yet and hence you are not receiving ads.  However without more information this cannot be confirmed. Please post above information on the [forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) and they will be able to assist you further. 

Regards,

Sam
